/**
 * ADM フェーズ知識ベース / ADM phase knowledge base.
 *
 * Preliminary, A〜H, Requirements Management の計 10 件。
 * 内容は独自の要約・実務解説であり、TOGAF 標準の原文の複製ではない。
 */

import type { AdmPhase } from './types.js';

export const ADM_PHASES: AdmPhase[] = [
  {
    id: 'preliminary',
    code: 'Preliminary',
    order: 0,
    name: { ja: '予備フェーズ', en: 'Preliminary Phase' },
    tagline: {
      ja: 'アーキテクチャを「やる体制」を整えるフェーズ',
      en: 'Set up the capability to do architecture at all',
    },
    purpose: {
      ja: 'アーキテクチャ作業そのものを始める前に、組織としてアーキテクチャを実践する能力(体制・原則・ガバナンス・手法・ツール)を用意する。ここを飛ばすと、後続フェーズの成果物が「誰の承認で、どの基準に照らして正しいのか」を説明できなくなる。',
      en: 'Before any architecture work starts, establish the organization\'s capability to practise architecture: the team, the principles, the governance bodies, the tailored method, and the tooling. Skipping this leaves later deliverables with no answer to "who approves this, and against which criteria?"',
    },
    inputs: [
      { ja: '経営戦略・中期経営計画・事業目標', en: 'Corporate strategy, mid-term business plan, business goals' },
      { ja: '既存のガバナンス体制・標準・規程(IT 統制、調達基準、セキュリティ規程)', en: 'Existing governance bodies, standards, and policies (IT controls, procurement rules, security policy)' },
      { ja: '既存のアーキテクチャ資産・EA リポジトリ(あれば)', en: 'Existing architecture assets and EA repository, if any' },
      { ja: '規制・法令要件、業界固有の枠組み', en: 'Regulatory and legal requirements, industry-specific frameworks' },
    ],
    steps: [
      { ja: '対象組織の範囲を決める(全社か、特定事業部か)', en: 'Scope the enterprise to be covered (whole company, or a specific business unit)' },
      { ja: '既存のフレームワーク・手法・組織構造を棚卸しする', en: 'Take inventory of frameworks, methods, and org structures already in use' },
      { ja: 'ADM を自組織向けにテーラリングする(不要な成果物を削り、既存プロセスと接続する)', en: 'Tailor the ADM to the organization: drop deliverables you will not use, and wire it into existing processes' },
      { ja: 'アーキテクチャ原則を策定し、経営層の承認を得る', en: 'Define architecture principles and get executive sign-off' },
      { ja: 'アーキテクチャガバナンスの枠組み(委員会・レビュー・例外処理)を定義する', en: 'Define the governance framework: boards, review gates, and the exception process' },
      { ja: 'EA リポジトリとツールを準備する', en: 'Stand up the EA repository and tooling' },
    ],
    outputs: [
      { ja: '組織モデル(アーキテクチャ実践のための体制図・役割定義)', en: 'Organizational model for enterprise architecture' },
      { ja: 'テーラリングされたアーキテクチャフレームワーク', en: 'Tailored architecture framework' },
      { ja: 'アーキテクチャ原則(承認済み)', en: 'Approved architecture principles' },
      { ja: 'アーキテクチャガバナンスの枠組みと初期の EA リポジトリ', en: 'Architecture governance framework and initial EA repository' },
    ],
    tips: [
      { ja: '原則は「守れる数」に絞る。20 個の美辞麗句より、判断に効く 8 個。各原則に「根拠」と「その原則を守ることで何を諦めるか」を必ず書く。', en: 'Keep principles to a number you can actually enforce. Eight decision-shaping principles beat twenty platitudes. For each one, write the rationale and what you give up by following it.' },
      { ja: 'テーラリングは「削る」作業だと割り切る。全成果物を作ろうとした瞬間にプロジェクトは形骸化する。', en: 'Treat tailoring as subtraction. The moment you try to produce every deliverable, the practice turns into paperwork.' },
      { ja: '既存のガバナンス会議体に相乗りできないか先に探す。新設した委員会は招集されなくなる。', en: 'Look first for an existing governance forum to attach to. Newly created boards quietly stop meeting.' },
      { ja: '「誰がアーキテクチャ決定を覆せるか」を最初に文書化する。これが曖昧な EA 組織は必ず失敗する。', en: 'Document up front who can overturn an architecture decision. EA teams that leave this vague always fail.' },
    ],
    deliverableIds: ['architecture-principles', 'request-for-architecture-work', 'organizational-model', 'tailored-framework'],
    techniqueIds: ['architecture-principles-technique', 'stakeholder-management', 'architecture-governance', 'architecture-maturity'],
    keywords: ['preliminary', '予備', '準備', '原則', 'principles', 'governance', 'ガバナンス', 'tailoring', 'テーラリング', '体制', 'setup', 'repository', 'リポジトリ'],
  },
  {
    id: 'a',
    code: 'A',
    order: 1,
    name: { ja: 'フェーズ A: アーキテクチャビジョン', en: 'Phase A: Architecture Vision' },
    tagline: {
      ja: '何を、なぜ、どこまでやるかを合意するフェーズ',
      en: 'Agree what the work is, why it matters, and where it stops',
    },
    purpose: {
      ja: 'アーキテクチャ作業の依頼を受け、対象範囲・制約・期待成果を明確にし、経営層が「これに投資する」と判断できる程度に具体的な将来像を描く。ここで得る承認(Statement of Architecture Work)が以降の全作業の権限の根拠になる。',
      en: 'Take the request for architecture work, pin down scope, constraints, and expected outcomes, and paint a target picture concrete enough for executives to fund. The approval obtained here — the Statement of Architecture Work — is the mandate for everything that follows.',
    },
    inputs: [
      { ja: 'アーキテクチャ作業依頼書(Request for Architecture Work)', en: 'Request for Architecture Work' },
      { ja: 'アーキテクチャ原則、ガバナンス枠組み(予備フェーズの成果)', en: 'Architecture principles and governance framework from the Preliminary Phase' },
      { ja: '事業戦略・事業目標・事業ドライバー', en: 'Business strategy, goals, and drivers' },
      { ja: '既存アーキテクチャ資産(現行のアーキテクチャ記述、標準)', en: 'Existing architecture assets: current descriptions and standards' },
    ],
    steps: [
      { ja: 'スポンサーを特定し、作業依頼の背景と成功条件を確認する', en: 'Identify the sponsor; confirm the background and success criteria behind the request' },
      { ja: 'ステークホルダーを洗い出し、関心事(concerns)と影響力を整理する', en: 'Identify stakeholders; map their concerns and influence' },
      { ja: '対象範囲・制約・前提を定義する(何を扱わないかも明記する)', en: 'Define scope, constraints, and assumptions — explicitly including what is out of scope' },
      { ja: 'ビジネス目標とドライバーを確認し、アーキテクチャ要件に翻訳する', en: 'Confirm business goals and drivers, and translate them into architecture requirements' },
      { ja: '現行の概要と目標の概要を高い抽象度で描き、ギャップの当たりをつける', en: 'Sketch baseline and target at a high level and take a first cut at the gaps' },
      { ja: 'ビジネス変革準備度を評価し、リスクを初期評価する', en: 'Assess business transformation readiness and make an initial risk assessment' },
      { ja: 'アーキテクチャ作業範囲記述書を作成し、承認を得る', en: 'Produce the Statement of Architecture Work and secure approval' },
    ],
    outputs: [
      { ja: 'アーキテクチャビジョン(将来像の概要)', en: 'Architecture Vision' },
      { ja: '承認済みアーキテクチャ作業範囲記述書', en: 'Approved Statement of Architecture Work' },
      { ja: 'ステークホルダーマップ、初期リスク評価', en: 'Stakeholder map and initial risk assessment' },
      { ja: '能力評価、ビジネス変革準備度評価', en: 'Capability assessment and business transformation readiness assessment' },
    ],
    tips: [
      { ja: 'ビジョンは「絵 1 枚 + 1 ページ」で説明できる濃さに保つ。詳細は B〜D で書けばよい。', en: 'Keep the vision at "one diagram plus one page". The detail belongs in Phases B–D.' },
      { ja: 'スコープ外の明記が最大のリスク対策。「今回やらないこと」を書面で合意しておくと、後の追加要求を正しく変更管理に回せる。', en: 'Writing down what is out of scope is your best risk control. Agreeing the "not this time" list in writing routes later requests into change management instead of scope creep.' },
      { ja: '成功条件を測定可能な形にする。「業務効率の向上」ではなく「月次決算を 5 営業日から 3 営業日に」。', en: 'Make success criteria measurable: not "improved efficiency" but "monthly close from five working days to three".' },
      { ja: 'スポンサーが誰かを 1 名に特定できないなら、まだ着手しない。合議制のスポンサーは意思決定を止める。', en: 'If you cannot name a single sponsor, do not start. A committee-as-sponsor stalls every decision.' },
    ],
    deliverableIds: ['architecture-vision', 'statement-of-architecture-work', 'request-for-architecture-work', 'stakeholder-map', 'communications-plan'],
    techniqueIds: ['business-scenarios', 'stakeholder-management', 'business-transformation-readiness', 'risk-management', 'gap-analysis'],
    keywords: ['vision', 'ビジョン', 'phase a', 'フェーズa', 'スコープ', 'scope', 'sow', 'statement of architecture work', 'スポンサー', 'sponsor', 'kickoff', '立ち上げ'],
  },
  {
    id: 'b',
    code: 'B',
    order: 2,
    name: { ja: 'フェーズ B: ビジネスアーキテクチャ', en: 'Phase B: Business Architecture' },
    tagline: {
      ja: '事業の仕組みを構造として記述するフェーズ',
      en: 'Describe how the business itself works, structurally',
    },
    purpose: {
      ja: 'ビジネス能力・バリューストリーム・組織・プロセス・情報の観点から、現行と目標のビジネスアーキテクチャを記述し、その差分を明らかにする。IT の議論に入る前に「事業として何ができるようになるのか」を固定する。',
      en: 'Describe baseline and target business architecture in terms of capabilities, value streams, organization, processes, and information, and expose the delta. This fixes "what the business will be able to do" before the IT conversation starts.',
    },
    inputs: [
      { ja: 'アーキテクチャビジョン、承認済み作業範囲記述書', en: 'Architecture Vision and approved Statement of Architecture Work' },
      { ja: 'アーキテクチャ原則(特にビジネス原則)', en: 'Architecture principles, business principles in particular' },
      { ja: '既存の業務プロセス定義、組織図、業務マニュアル', en: 'Existing process definitions, org charts, operating manuals' },
      { ja: 'ビジネス能力モデル・バリューストリーム(あれば)', en: 'Business capability model and value streams, if they exist' },
    ],
    steps: [
      { ja: '参照モデル・視点・ツールを選定する', en: 'Select reference models, viewpoints, and tools' },
      { ja: '現行ビジネスアーキテクチャを必要な範囲だけ記述する', en: 'Describe the baseline business architecture — only as far as you need it' },
      { ja: '目標ビジネスアーキテクチャを記述する(能力・バリューストリーム・プロセス・組織)', en: 'Describe the target business architecture: capabilities, value streams, processes, organization' },
      { ja: 'ギャップ分析を実施する', en: 'Perform gap analysis' },
      { ja: '候補となるロードマップ構成要素を洗い出す', en: 'Identify candidate roadmap components' },
      { ja: '他アーキテクチャ領域への影響を確認し、ステークホルダーレビューを行う', en: 'Check impacts on the other architecture domains and run a stakeholder review' },
    ],
    outputs: [
      { ja: 'ビジネスアーキテクチャ部分のアーキテクチャ定義書', en: 'Business section of the Architecture Definition Document' },
      { ja: 'ビジネス能力マップ、バリューストリームマップ、組織/機能マトリクス', en: 'Business capability map, value stream map, organization/function matrix' },
      { ja: 'ビジネスアーキテクチャ要件仕様', en: 'Business architecture requirements specification' },
      { ja: '更新されたギャップ一覧とロードマップ候補', en: 'Updated gap list and candidate roadmap components' },
    ],
    tips: [
      { ja: '現行の記述は「ギャップを語るのに必要な粒度」で止める。現行分析に半年かけた案件は目標像に到達しない。', en: 'Describe the baseline only to the depth needed to argue about gaps. Projects that spend six months on as-is analysis never reach the target.' },
      { ja: '能力(capability)とプロセスを混ぜない。能力は「何ができるか」、プロセスは「どうやるか」。混ぜると組織再編のたびにモデルが壊れる。', en: 'Do not blend capability with process. Capability is what you can do; process is how you do it. Blend them and the model breaks at every reorg.' },
      { ja: '各能力に「誰が責任者か」を紐付ける。持ち主のいない能力は誰も改善しない。', en: 'Attach an owner to every capability. Nobody improves a capability that has no owner.' },
      { ja: '業務部門の言葉で書く。ここに IT 用語が混ざり始めたら、フェーズ B としては失敗している。', en: 'Write in the language of the business. Once IT vocabulary creeps in, Phase B has already failed.' },
    ],
    deliverableIds: ['architecture-definition-document', 'architecture-requirements-spec', 'business-capability-map', 'architecture-roadmap'],
    techniqueIds: ['gap-analysis', 'business-scenarios', 'capability-based-planning', 'stakeholder-management', 'business-transformation-readiness'],
    keywords: ['business architecture', 'ビジネスアーキテクチャ', 'phase b', 'フェーズb', '能力', 'capability', 'value stream', 'バリューストリーム', 'プロセス', 'process', '業務'],
  },
  {
    id: 'c',
    code: 'C',
    order: 3,
    name: { ja: 'フェーズ C: 情報システムアーキテクチャ(データ/アプリケーション)', en: 'Phase C: Information Systems Architectures (Data and Application)' },
    tagline: {
      ja: 'データとアプリケーションの構造を決めるフェーズ',
      en: 'Decide the structure of data and applications',
    },
    purpose: {
      ja: 'ビジネスアーキテクチャを支えるデータアーキテクチャとアプリケーションアーキテクチャを、現行・目標の両面で記述する。どの業務データをどこが正とし、どのアプリケーションがどの能力を実現するかを確定させる。',
      en: 'Describe the data and application architectures that support the business architecture, baseline and target. Settle which system is the source of truth for which data, and which application realizes which capability.',
    },
    inputs: [
      { ja: '目標ビジネスアーキテクチャとビジネス要件', en: 'Target business architecture and business requirements' },
      { ja: 'データ原則・データ管理方針、既存のデータモデル', en: 'Data principles, data management policy, existing data models' },
      { ja: 'アプリケーションポートフォリオ(現行システム一覧)', en: 'Application portfolio: the inventory of current systems' },
      { ja: '関連する規制要件(個人情報保護、データ所在地要件など)', en: 'Applicable regulatory requirements such as privacy and data residency' },
    ],
    steps: [
      { ja: 'データアーキテクチャ: 主要データエンティティを定義し、システムとの関係を整理する', en: 'Data: define the key data entities and map them to systems' },
      { ja: 'データの正本(system of record)とライフサイクルを決める', en: 'Data: designate the system of record and the lifecycle for each entity' },
      { ja: 'アプリケーションアーキテクチャ: 論理アプリケーション構成要素と機能を定義する', en: 'Application: define logical application components and their functions' },
      { ja: 'アプリケーションと業務機能・データのマトリクスを作る', en: 'Application: build the application/function and application/data matrices' },
      { ja: '統合方式(連携パターン、API、イベント)を決める', en: 'Decide the integration approach: patterns, APIs, events' },
      { ja: 'ギャップ分析を行い、ロードマップ候補を更新する', en: 'Run gap analysis and update candidate roadmap components' },
    ],
    outputs: [
      { ja: 'データ/アプリケーション部分のアーキテクチャ定義書', en: 'Data and application sections of the Architecture Definition Document' },
      { ja: 'データエンティティ/ビジネス機能マトリクス、システム/データ CRUD マトリクス', en: 'Data entity/business function matrix and system/data CRUD matrix' },
      { ja: 'アプリケーションポートフォリオカタログ、インターフェースカタログ', en: 'Application portfolio catalog and interface catalog' },
      { ja: '情報システムアーキテクチャ要件仕様', en: 'Information systems architecture requirements specification' },
    ],
    tips: [
      { ja: 'データの正本を 1 エンティティにつき 1 システムに決め切る。「両方が正」を許した瞬間に統合コストが青天井になる。', en: 'Force exactly one system of record per entity. The moment you allow "both are authoritative", integration cost goes unbounded.' },
      { ja: '論理と物理を分ける。製品名(SAP, Salesforce)が論理アプリケーション構成要素の名前になっていたら書き直す。', en: 'Separate logical from physical. If a product name (SAP, Salesforce) is serving as the name of a logical component, rewrite it.' },
      { ja: 'CRUD マトリクスは万能ではないが、「作成する主体が複数ある」データを炙り出す道具としては極めて有効。', en: 'The CRUD matrix is not a silver bullet, but it is an excellent detector of data that more than one system claims to create.' },
      { ja: 'インターフェース数は複雑性の代理指標。目標像で連携本数が増えているなら、統合基盤の議論を F の前に始める。', en: 'Interface count is a proxy for complexity. If the target grows the number of point-to-point links, start the integration-platform conversation before Phase F.' },
    ],
    deliverableIds: ['architecture-definition-document', 'architecture-requirements-spec', 'application-portfolio-catalog', 'data-entity-catalog', 'architecture-roadmap'],
    techniqueIds: ['gap-analysis', 'interoperability-requirements', 'capability-based-planning', 'stakeholder-management'],
    keywords: ['information systems', '情報システム', 'data architecture', 'データアーキテクチャ', 'application', 'アプリケーション', 'phase c', 'フェーズc', 'crud', 'api', '連携', 'integration', 'マスタデータ', 'master data'],
  },
  {
    id: 'd',
    code: 'D',
    order: 4,
    name: { ja: 'フェーズ D: テクノロジーアーキテクチャ', en: 'Phase D: Technology Architecture' },
    tagline: {
      ja: 'アプリケーションを載せる技術基盤を決めるフェーズ',
      en: 'Decide the technology platform the applications will run on',
    },
    purpose: {
      ja: 'データ/アプリケーションアーキテクチャを実現する技術基盤(プラットフォーム、ネットワーク、実行環境、運用・監視、セキュリティ基盤)を現行・目標の両面で記述する。非機能要件がここで初めて具体的なサイジングと構成に落ちる。',
      en: 'Describe the technology platform — compute, network, runtime, operations, security services — that realizes the data and application architectures, baseline and target. This is where non-functional requirements finally become concrete sizing and configuration.',
    },
    inputs: [
      { ja: '目標アプリケーション/データアーキテクチャ', en: 'Target application and data architectures' },
      { ja: '非機能要件(性能、可用性、RTO/RPO、拡張性、セキュリティ)', en: 'Non-functional requirements: performance, availability, RTO/RPO, scalability, security' },
      { ja: '技術標準・技術ポートフォリオ、既存インフラ構成', en: 'Technology standards and portfolio, existing infrastructure configuration' },
      { ja: '調達・ベンダー制約、既存契約', en: 'Procurement and vendor constraints, existing contracts' },
    ],
    steps: [
      { ja: '参照モデル・技術標準を選定する', en: 'Select reference models and technology standards' },
      { ja: '現行技術構成を必要な範囲で記述する', en: 'Describe the baseline technology configuration as far as needed' },
      { ja: '目標技術アーキテクチャを記述する(プラットフォーム、ネットワーク、運用、セキュリティ)', en: 'Describe the target technology architecture: platform, network, operations, security' },
      { ja: '非機能要件を配置・冗長化・サイジングに落とす', en: 'Translate non-functional requirements into placement, redundancy, and sizing' },
      { ja: 'ギャップ分析を行い、技術的な移行の順序制約を洗い出す', en: 'Run gap analysis and surface sequencing constraints imposed by technology' },
      { ja: 'ステークホルダーレビュー(特に運用・セキュリティ部門)を行う', en: 'Review with stakeholders, especially operations and security' },
    ],
    outputs: [
      { ja: 'テクノロジー部分のアーキテクチャ定義書', en: 'Technology section of the Architecture Definition Document' },
      { ja: '技術標準カタログ、技術ポートフォリオカタログ', en: 'Technology standards catalog and technology portfolio catalog' },
      { ja: '環境配置図、ネットワーク構成図', en: 'Environments and locations diagram, network computing diagram' },
      { ja: 'テクノロジーアーキテクチャ要件仕様', en: 'Technology architecture requirements specification' },
    ],
    tips: [
      { ja: '運用部門を D の途中で呼ぶのではなく、最初から入れる。運用が納得していない技術構成は本番で必ず揉める。', en: 'Bring operations in at the start of Phase D, not midway. A platform operations never agreed to will bite you in production.' },
      { ja: '技術標準は「推奨・許容・非推奨・廃止予定」の 4 段階で管理する。二値(可/不可)にすると例外申請だらけになる。', en: 'Manage standards in four states — preferred, acceptable, discouraged, retiring. A binary allow/deny list produces nothing but exception requests.' },
      { ja: '可用性要件は金額に換算して確認する。「24/365 必須」と言った部門に冗長化コストを提示すると要件が現実的になる。', en: 'Price availability requirements. Showing the cost of redundancy to the team that demanded 24/365 makes the requirement realistic fast.' },
      { ja: 'クラウド前提でも、データ所在地・出口コスト・ロックインの 3 点は必ず明示的に評価する。', en: 'Even on a cloud-first mandate, always evaluate three things explicitly: data residency, egress cost, and lock-in.' },
    ],
    deliverableIds: ['architecture-definition-document', 'architecture-requirements-spec', 'technology-standards-catalog', 'architecture-roadmap'],
    techniqueIds: ['gap-analysis', 'interoperability-requirements', 'risk-management', 'stakeholder-management'],
    keywords: ['technology', 'テクノロジー', 'インフラ', 'infrastructure', 'phase d', 'フェーズd', 'platform', 'プラットフォーム', 'cloud', 'クラウド', '非機能', 'non-functional', 'network', 'ネットワーク'],
  },
  {
    id: 'e',
    code: 'E',
    order: 5,
    name: { ja: 'フェーズ E: 機会とソリューション', en: 'Phase E: Opportunities and Solutions' },
    tagline: {
      ja: 'ギャップを実行可能な塊にまとめるフェーズ',
      en: 'Bundle the gaps into things that can actually be delivered',
    },
    purpose: {
      ja: 'B〜D で洗い出したギャップを整理し、実装可能な作業パッケージ、移行アーキテクチャ(中間状態)、そして全体のロードマップに組み立てる。ここが「アーキテクチャ」から「実行計画」への転換点。',
      en: 'Consolidate the gaps from Phases B–D into deliverable work packages, transition architectures (intermediate states), and an overall roadmap. This is the pivot from architecture to executable plan.',
    },
    inputs: [
      { ja: 'B〜D のギャップ一覧と候補ロードマップ構成要素', en: 'Consolidated gaps and candidate roadmap components from Phases B–D' },
      { ja: 'ビジネス変革準備度評価、リスク評価', en: 'Business transformation readiness assessment and risk assessment' },
      { ja: '既存プロジェクト・投資計画の一覧', en: 'Inventory of in-flight projects and the investment plan' },
      { ja: '制約(予算、要員、期限、規制対応期日)', en: 'Constraints: budget, staffing, deadlines, regulatory dates' },
    ],
    steps: [
      { ja: '全ギャップを統合して重複を排除する', en: 'Consolidate all gaps and remove duplicates' },
      { ja: '依存関係と業務価値でギャップを作業パッケージに束ねる', en: 'Group gaps into work packages by dependency and business value' },
      { ja: '実装アプローチを決める(自社開発/パッケージ/SaaS、段階移行/一括移行)', en: 'Decide the implementation approach: build/buy/SaaS, phased or big-bang' },
      { ja: '移行アーキテクチャ(中間状態)を定義する — 各状態が単独で価値を出せることを確認する', en: 'Define transition architectures — verify each intermediate state delivers value on its own' },
      { ja: '既存プロジェクトとの整合を取り、重複投資を潰す', en: 'Align with in-flight projects and kill duplicated investment' },
      { ja: 'アーキテクチャロードマップの初版を作る', en: 'Produce the first version of the Architecture Roadmap' },
    ],
    outputs: [
      { ja: 'アーキテクチャロードマップ(初版)', en: 'Architecture Roadmap, first version' },
      { ja: '作業パッケージ定義、移行アーキテクチャ', en: 'Work package definitions and transition architectures' },
      { ja: '実装・移行戦略、更新された影響評価', en: 'Implementation and migration strategy, updated impact assessment' },
      { ja: '更新されたアーキテクチャ定義書', en: 'Updated Architecture Definition Document' },
    ],
    tips: [
      { ja: '中間状態は「そこで止まっても事業が回る」ことを必須条件にする。止まれない中間状態は、予算が切れた瞬間に負債になる。', en: 'Require that every transition state can be stopped at without breaking the business. A state you cannot stop at becomes debt the day the budget is cut.' },
      { ja: '作業パッケージは「1 チームが 3〜6 か月で完了できる」大きさを目安にする。年単位のパッケージは進捗が見えない。', en: 'Size work packages so one team can finish one in three to six months. Year-long packages hide their own progress.' },
      { ja: '既存の走行中プロジェクトの棚卸しをここで必ずやる。EA が新規計画だけ作ると、現場では二重投資が進行する。', en: 'Inventory in-flight projects here without fail. An EA plan that ignores them just funds the same thing twice.' },
      { ja: '「やらない案」を 1 つ必ずロードマップに併記する。比較対象があると投資判断が速い。', en: 'Always carry a "do nothing" option alongside the roadmap. Investment decisions move faster when there is something to compare against.' },
    ],
    deliverableIds: ['architecture-roadmap', 'transition-architecture', 'implementation-migration-plan', 'architecture-definition-document'],
    techniqueIds: ['gap-analysis', 'capability-based-planning', 'migration-planning-techniques', 'risk-management', 'business-transformation-readiness'],
    keywords: ['opportunities', 'solutions', '機会', 'ソリューション', 'phase e', 'フェーズe', 'roadmap', 'ロードマップ', 'work package', '作業パッケージ', 'transition', '移行', '中間状態'],
  },
  {
    id: 'f',
    code: 'F',
    order: 6,
    name: { ja: 'フェーズ F: 移行計画', en: 'Phase F: Migration Planning' },
    tagline: {
      ja: 'ロードマップを予算と体制の付いた計画に変えるフェーズ',
      en: 'Turn the roadmap into a funded, staffed plan',
    },
    purpose: {
      ja: 'アーキテクチャロードマップを、優先順位・コスト・便益・体制が裏付けられた実装移行計画に仕上げ、既存のポートフォリオ管理・プロジェクト管理プロセスに引き渡す。',
      en: 'Finalize the roadmap into an implementation and migration plan backed by priorities, cost, benefit, and staffing, and hand it over to the existing portfolio and project management processes.',
    },
    inputs: [
      { ja: 'アーキテクチャロードマップ、作業パッケージ、移行アーキテクチャ', en: 'Architecture Roadmap, work packages, transition architectures' },
      { ja: 'コスト・便益の見積り、資源の制約', en: 'Cost/benefit estimates and resource constraints' },
      { ja: '既存のポートフォリオ管理プロセス、予算サイクル', en: 'Existing portfolio management process and budget cycle' },
      { ja: 'リスク登録簿', en: 'Risk register' },
    ],
    steps: [
      { ja: '各作業パッケージのコスト・便益・リスクを見積もる', en: 'Estimate cost, benefit, and risk for each work package' },
      { ja: '価値と依存関係で優先順位を付ける', en: 'Prioritize by value and dependency' },
      { ja: '実装移行計画を作成する(体制、マイルストーン、予算配分)', en: 'Build the implementation and migration plan: staffing, milestones, budget allocation' },
      { ja: '残存リスクを評価し、対応策と受容判断を文書化する', en: 'Assess residual risk; document mitigations and acceptance decisions' },
      { ja: '既存のポートフォリオ/プロジェクト管理へ移管する', en: 'Transfer into the existing portfolio and project management framework' },
      { ja: 'アーキテクチャ契約(Architecture Contract)の準備を始める', en: 'Begin preparing the Architecture Contract' },
    ],
    outputs: [
      { ja: '実装移行計画(承認済み)', en: 'Approved Implementation and Migration Plan' },
      { ja: '確定したアーキテクチャロードマップと移行アーキテクチャ', en: 'Finalized Architecture Roadmap and transition architectures' },
      { ja: '更新されたアーキテクチャ定義書・要件仕様', en: 'Updated Architecture Definition Document and requirements specification' },
      { ja: '実装ガバナンスモデル', en: 'Implementation governance model' },
    ],
    tips: [
      { ja: '組織の予算サイクルに合わせて計画を刻む。会計年度をまたぐ大きな塊は承認されないか、途中で削られる。', en: 'Cut the plan to the organization\'s budget cycle. Big chunks that straddle fiscal years either fail to get approved or get trimmed midway.' },
      { ja: '便益は誰が刈り取るのかを名指しで書く。便益責任者のいない施策は、完了しても効果測定されない。', en: 'Name who will harvest each benefit. Initiatives without a benefit owner are never measured after delivery.' },
      { ja: 'クリティカルパス上の作業パッケージには必ず代替案を用意しておく。', en: 'Every work package on the critical path needs a fallback option prepared in advance.' },
      { ja: '移管はドキュメントを渡すことではなく、PMO と受け入れ基準を合意すること。', en: 'Handover is not sending documents; it is agreeing acceptance criteria with the PMO.' },
    ],
    deliverableIds: ['implementation-migration-plan', 'architecture-roadmap', 'transition-architecture', 'architecture-contract'],
    techniqueIds: ['migration-planning-techniques', 'risk-management', 'capability-based-planning', 'gap-analysis'],
    keywords: ['migration planning', '移行計画', 'phase f', 'フェーズf', 'コスト', 'cost', 'benefit', '便益', '優先順位', 'prioritization', 'portfolio', 'ポートフォリオ', '予算', 'budget'],
  },
  {
    id: 'g',
    code: 'G',
    order: 7,
    name: { ja: 'フェーズ G: 実装ガバナンス', en: 'Phase G: Implementation Governance' },
    tagline: {
      ja: '作られたものが設計どおりか見張るフェーズ',
      en: 'Make sure what gets built matches what was designed',
    },
    purpose: {
      ja: '実装プロジェクトに対してアーキテクチャの観点から助言・監督を行い、設計との適合を確認する。アーキテクチャ契約を通じて、実装チームに守るべき制約と例外申請の道筋を与える。',
      en: 'Advise and oversee the implementation projects from an architecture standpoint and verify conformance with the design. The Architecture Contract gives delivery teams both the constraints to honour and a legitimate route to request exceptions.',
    },
    inputs: [
      { ja: '実装移行計画、アーキテクチャ定義書、要件仕様', en: 'Implementation and Migration Plan, Architecture Definition Document, requirements specification' },
      { ja: 'アーキテクチャ契約(実装チームとの合意)', en: 'Architecture Contract agreed with the delivery teams' },
      { ja: 'ガバナンス枠組み(予備フェーズの成果)', en: 'Governance framework from the Preliminary Phase' },
      { ja: '実装プロジェクトの設計書・進捗報告', en: 'Design documents and status reports from implementation projects' },
    ],
    steps: [
      { ja: '実装プロジェクトごとにアーキテクチャ契約を締結する', en: 'Put an Architecture Contract in place for each implementation project' },
      { ja: 'アーキテクチャ適合性レビューを設計の節目で実施する', en: 'Run architecture compliance reviews at design milestones' },
      { ja: '逸脱を検出し、是正か例外承認かを判断する', en: 'Detect deviations and decide between remediation and a granted exception' },
      { ja: '例外を台帳で管理し、期限と解消計画を付ける', en: 'Track exceptions in a register with an expiry date and a remediation plan' },
      { ja: '実装からの学びをアーキテクチャに反映する', en: 'Feed lessons from implementation back into the architecture' },
      { ja: '稼働後、便益が実現されているか確認する', en: 'After go-live, verify that the expected benefits are materializing' },
    ],
    outputs: [
      { ja: 'アーキテクチャ適合性評価結果', en: 'Architecture compliance assessments' },
      { ja: '締結済みアーキテクチャ契約、例外台帳', en: 'Signed Architecture Contracts and the exception register' },
      { ja: '実装システム(アーキテクチャ準拠が確認されたもの)', en: 'Implemented systems with confirmed architecture conformance' },
      { ja: '変更要求(実装から生じたもの)', en: 'Change requests arising from implementation' },
    ],
    tips: [
      { ja: 'レビューは「合否判定」ではなく「設計相談」の場として設計する。査問会になった瞬間、実装チームは相談に来なくなる。', en: 'Design reviews as design consultations, not pass/fail tribunals. The moment it feels like an inquisition, delivery teams stop coming.' },
      { ja: '例外には必ず期限を付ける。期限のない例外は永久の標準になる。', en: 'Every exception gets an expiry date. An exception without one becomes the permanent standard.' },
      { ja: '適合性チェック項目は 1 ページに収める。100 項目のチェックリストは形式的に埋められるだけ。', en: 'Keep the conformance checklist to one page. A hundred-item checklist just gets ticked mechanically.' },
      { ja: '同じ逸脱が 3 回起きたら、実装チームではなくアーキテクチャの方を疑う。', en: 'If the same deviation shows up three times, suspect the architecture, not the delivery teams.' },
    ],
    deliverableIds: ['architecture-contract', 'compliance-assessment', 'implementation-migration-plan', 'architecture-definition-document'],
    techniqueIds: ['architecture-governance', 'risk-management', 'stakeholder-management'],
    keywords: ['implementation governance', '実装ガバナンス', 'phase g', 'フェーズg', 'compliance', '適合性', 'contract', '契約', 'review', 'レビュー', '例外', 'exception'],
  },
  {
    id: 'h',
    code: 'H',
    order: 8,
    name: { ja: 'フェーズ H: アーキテクチャ変更管理', en: 'Phase H: Architecture Change Management' },
    tagline: {
      ja: '変化を受け止め、次のサイクルを起動するフェーズ',
      en: 'Absorb change and decide when to start the next cycle',
    },
    purpose: {
      ja: '稼働後のアーキテクチャを継続的に監視し、事業環境・技術・要件の変化に対して、軽微な修正で済むのか、新たな ADM サイクルを回すべきかを判断する。EA を「作って終わり」にしないための仕組み。',
      en: 'Continuously monitor the architecture in operation and judge whether changes in business, technology, or requirements can be absorbed as maintenance or demand a new ADM cycle. This is what keeps EA from being a one-off exercise.',
    },
    inputs: [
      { ja: '稼働中のアーキテクチャ、適合性評価結果', en: 'Architecture in operation and compliance assessments' },
      { ja: '変更要求(事業側・技術側・実装側から)', en: 'Change requests from business, technology, and delivery' },
      { ja: '技術動向、事業環境の変化、規制変更', en: 'Technology trends, changes in the business environment, regulatory changes' },
      { ja: '便益実現の測定結果、運用上の課題', en: 'Benefit realization measurements and operational issues' },
    ],
    steps: [
      { ja: '変更を監視する仕組みを回す(技術動向、事業指標、インシデント)', en: 'Operate the monitoring loop: technology watch, business metrics, incidents' },
      { ja: '変更要求を受け付け、影響を評価する', en: 'Receive change requests and assess their impact' },
      { ja: '変更を分類する — 簡素化(維持)/漸進的(部分改訂)/再アーキテクチャ(新サイクル)', en: 'Classify the change: simplification (maintain), incremental (partial revision), or re-architecting (new cycle)' },
      { ja: '分類に応じてアーキテクチャ委員会に諮り、判断を得る', en: 'Take the classification to the architecture board for a decision' },
      { ja: '維持で済むものはアーキテクチャ資産を更新する', en: 'For maintenance-level changes, update the architecture assets' },
      { ja: '新サイクルが必要なものはフェーズ A への作業依頼として起票する', en: 'For re-architecting, raise a Request for Architecture Work into Phase A' },
    ],
    outputs: [
      { ja: 'アーキテクチャ更新(維持レベルの変更)', en: 'Architecture updates for maintenance-level changes' },
      { ja: '新規のアーキテクチャ作業依頼書(新サイクル起動)', en: 'New Requests for Architecture Work that start the next cycle' },
      { ja: 'アーキテクチャ適合性の継続評価、更新された EA リポジトリ', en: 'Ongoing conformance assessments and an updated EA repository' },
      { ja: '変更管理の記録・決定ログ', en: 'Change management records and decision log' },
    ],
    tips: [
      { ja: '「どこまでが維持で、どこからが新サイクルか」の基準を先に決めておく。都度議論すると、政治的に楽な「維持」に倒れ続けて破綻する。', en: 'Set the maintain-versus-re-architect threshold in advance. Argued case by case, it always drifts toward the politically easy "maintain" until the architecture collapses.' },
      { ja: '変更要求の受付窓口を 1 つにする。複数経路があると、アーキテクチャは知らないうちに書き換えられる。', en: 'Keep a single intake for change requests. Multiple routes mean the architecture gets rewritten without you knowing.' },
      { ja: 'H は「守り」ではなく、次の投資機会を見つけるフェーズだと位置づけると、経営層の関心を維持しやすい。', en: 'Frame Phase H as the place where the next investment opportunity is found, not as defence. It keeps executive attention alive.' },
      { ja: '例外台帳の棚卸しを定例化する。ここが H の一番現実的な入口。', en: 'Put a recurring review of the exception register on the calendar. It is the most practical entry point into Phase H.' },
    ],
    deliverableIds: ['request-for-architecture-work', 'compliance-assessment', 'architecture-definition-document', 'architecture-repository'],
    techniqueIds: ['architecture-governance', 'risk-management', 'architecture-maturity', 'business-transformation-readiness'],
    keywords: ['change management', '変更管理', 'phase h', 'フェーズh', '運用', 'operation', 'monitoring', '監視', '継続', 'continuous', '再アーキテクチャ'],
  },
  {
    id: 'requirements-management',
    code: 'RM',
    order: 9,
    name: { ja: '要件管理', en: 'Requirements Management' },
    tagline: {
      ja: '全フェーズを貫く、要件の出入りを管理する活動',
      en: 'The continuous activity that governs requirements across every phase',
    },
    purpose: {
      ja: 'ADM の中心に位置し、全フェーズで発生・変更される要件を受け付け、保管し、影響を評価し、該当フェーズへ差し戻す。フェーズではなく「常時動いているプロセス」である点が重要。',
      en: 'Sits at the centre of the ADM: receive, store, assess the impact of, and dispatch requirements that arise or change in any phase. Crucially it is a continuously running process, not a phase you pass through.',
    },
    inputs: [
      { ja: '各フェーズで発生した新規・変更要件', en: 'New and changed requirements raised in any phase' },
      { ja: 'ビジネスシナリオ、ステークホルダーの関心事', en: 'Business scenarios and stakeholder concerns' },
      { ja: '規制要件、非機能要件', en: 'Regulatory and non-functional requirements' },
      { ja: '実装フェーズからのフィードバック', en: 'Feedback from implementation' },
    ],
    steps: [
      { ja: '要件を識別し、一意の ID と出所を付けて記録する', en: 'Identify each requirement and record it with a unique ID and its source' },
      { ja: '優先度・重要度を付与する', en: 'Assign priority and criticality' },
      { ja: '変更が生じたら影響範囲(どのフェーズ・成果物に及ぶか)を評価する', en: 'When a change occurs, assess which phases and deliverables it touches' },
      { ja: '影響を受けるフェーズに要件を差し戻し、再作業の要否を判断する', en: 'Dispatch the requirement back to the affected phases and decide whether rework is needed' },
      { ja: '要件の状態(提案/承認/実装済/却下)を追跡する', en: 'Track requirement state: proposed, approved, implemented, rejected' },
      { ja: 'トレーサビリティ(要件 ↔ 成果物 ↔ 実装)を維持する', en: 'Maintain traceability from requirement to deliverable to implementation' },
    ],
    outputs: [
      { ja: 'アーキテクチャ要件仕様(維持されたもの)', en: 'A maintained Architecture Requirements Specification' },
      { ja: '要件影響評価', en: 'Requirements impact assessments' },
      { ja: '要件トレーサビリティマトリクス', en: 'Requirements traceability matrix' },
      { ja: '各フェーズへの差し戻し指示', en: 'Dispatch instructions to the affected phases' },
    ],
    tips: [
      { ja: '要件は必ず出所(誰の、どの発言・どの文書か)を残す。出所不明の要件は削除の判断ができず、永久に残る。', en: 'Always record where a requirement came from — whose statement, which document. Requirements with no traceable origin can never be safely deleted, so they live forever.' },
      { ja: '「却下した要件」も記録して残す。同じ要求が半年後に別の人から必ず再提出される。', en: 'Keep rejected requirements on record. The same ask always comes back six months later from someone else.' },
      { ja: '要件管理をツールに丸投げしない。重要なのは「変わったときに誰に伝わるか」の経路設計。', en: 'Do not outsource requirements management to a tool. What matters is the routing: who gets told when something changes.' },
      { ja: '非機能要件こそ ID を振って管理する。機能要件は忘れられないが、非機能要件は静かに消える。', en: 'Give non-functional requirements IDs above all. Functional requirements are never forgotten; non-functional ones vanish quietly.' },
    ],
    deliverableIds: ['architecture-requirements-spec', 'requirements-impact-assessment', 'architecture-definition-document'],
    techniqueIds: ['business-scenarios', 'gap-analysis', 'stakeholder-management', 'risk-management'],
    keywords: ['requirements', '要件', 'requirements management', '要件管理', 'traceability', 'トレーサビリティ', 'rm', '変更', 'change', '非機能'],
  },
];

/** ID(大文字小文字・'phase a' 形式も許容)からフェーズを引く */
export function findPhase(idOrCode: string): AdmPhase | undefined {
  const key = idOrCode.trim().toLowerCase().replace(/^phase\s+/, '').replace(/^フェーズ\s*/, '');
  return ADM_PHASES.find(
    (p) => p.id === key || p.code.toLowerCase() === key || p.id.replace(/-/g, ' ') === key,
  );
}
