/**
 * 成果物の知識ベース / Deliverables knowledge base.
 * 独自の要約・実務解説。原文の転載はしない。
 */

import type { Deliverable } from './types.js';

export const DELIVERABLES: Deliverable[] = [
  {
    id: 'request-for-architecture-work',
    name: { ja: 'アーキテクチャ作業依頼書', en: 'Request for Architecture Work' },
    summary: {
      ja: 'アーキテクチャ作業を開始する引き金となる文書。スポンサー側が「何を、なぜ、いつまでに検討してほしいのか」を記述する。ADM サイクルの起点であり、フェーズ H から次サイクルを起動する際にも使う。',
      en: 'The document that triggers architecture work. The sponsoring side states what should be examined, why, and by when. It starts an ADM cycle — including the next cycle raised out of Phase H.',
    },
    createdInPhaseIds: ['preliminary', 'h'],
    refinedInPhaseIds: ['a'],
    contents: [
      { ja: '依頼元組織・スポンサー・責任者', en: 'Requesting organization, sponsor, and accountable executive' },
      { ja: '事業上の背景・課題・変革の動機', en: 'Business context, problem, and the motivation to change' },
      { ja: '検討してほしい範囲と、明示的に対象外とする範囲', en: 'Scope to be examined and what is explicitly excluded' },
      { ja: '既知の制約(予算、期限、規制、既存契約)', en: 'Known constraints: budget, deadline, regulation, existing contracts' },
      { ja: '期待する成果と成功条件', en: 'Expected outcomes and success criteria' },
      { ja: '関連する既存の取り組み・進行中プロジェクト', en: 'Related initiatives and in-flight projects' },
    ],
    tips: [
      { ja: '依頼書が来ないまま作業が始まる案件は多い。その場合はアーキテクト側で草案を書き、スポンサーに承認させるのが現実的。', en: 'Work often starts without one. The practical move is to draft it yourself and have the sponsor approve it.' },
      { ja: '「解決策」が依頼書に書かれていたら、それを要求ではなく仮説として扱う。', en: 'If a solution is already named in the request, treat it as a hypothesis, not a requirement.' },
    ],
    keywords: ['request', '依頼書', 'raw', 'architecture work', '起点', 'トリガー', '作業依頼'],
    template: [
      { heading: { ja: '1. 依頼の概要', en: '1. Request Summary' }, guidance: { ja: '誰が、何を、なぜ依頼するのかを 3〜5 行で。', en: 'Who is asking for what, and why, in three to five lines.' } },
      { heading: { ja: '2. 事業上の背景と課題', en: '2. Business Context and Problem' }, guidance: { ja: '事業指標・現場の痛み・外部環境の変化を具体的に書く。', en: 'Business metrics, operational pain, and external change — concretely.' } },
      { heading: { ja: '3. 対象範囲 / 対象外', en: '3. In Scope / Out of Scope' }, guidance: { ja: '対象外を書くことが最大のリスク対策。', en: 'Writing the out-of-scope list is the strongest risk control here.' } },
      { heading: { ja: '4. 制約と前提', en: '4. Constraints and Assumptions' }, guidance: { ja: '予算・期限・規制・既存契約・技術標準。', en: 'Budget, deadline, regulation, contracts, technology standards.' } },
      { heading: { ja: '5. 期待成果と成功条件', en: '5. Expected Outcomes and Success Criteria' }, guidance: { ja: '測定可能な数値で書く。', en: 'Write measurable numbers.' } },
      { heading: { ja: '6. スポンサーと承認', en: '6. Sponsor and Approval' }, guidance: { ja: 'スポンサーは 1 名。承認日を記録する。', en: 'A single named sponsor. Record the approval date.' } },
    ],
  },
  {
    id: 'architecture-principles',
    name: { ja: 'アーキテクチャ原則', en: 'Architecture Principles' },
    summary: {
      ja: '組織として合意した、アーキテクチャ判断の基準。各原則を「名称・記述・根拠・含意」の 4 点で記述する。レビューや技術選定で実際に参照されて初めて価値が出る。',
      en: 'The agreed criteria for architecture decisions, each written as name, statement, rationale, and implications. They only pay off once they are actually cited in reviews and technology selections.',
    },
    createdInPhaseIds: ['preliminary'],
    refinedInPhaseIds: ['a', 'g', 'h'],
    contents: [
      { ja: '原則の名称(短く、記憶できるもの)', en: 'Principle name — short and memorable' },
      { ja: '記述(何を守るのかを一文で)', en: 'Statement — what is to be upheld, in one sentence' },
      { ja: '根拠(なぜそうするのか、事業上の理由)', en: 'Rationale — the business reason' },
      { ja: '含意(守ることで生じる制約・コスト・諦めるもの)', en: 'Implications — the constraints, costs, and trade-offs of honouring it' },
      { ja: '原則間の優先順位', en: 'Precedence between principles' },
    ],
    tips: [
      { ja: '含意を書けない原則は、まだ原則になっていない。', en: 'If you cannot write the implications, it is not yet a principle.' },
      { ja: '8 個前後に絞る。数を増やすほど拘束力が下がる。', en: 'Aim for around eight. The more you add, the less binding any of them are.' },
    ],
    keywords: ['principle', '原則', 'アーキテクチャ原則', '判断基準', 'rationale', 'implications'],
    template: [
      { heading: { ja: '原則 N: <名称>', en: 'Principle N: <name>' }, guidance: { ja: '以下の 4 項目を各原則ごとに繰り返す。', en: 'Repeat the four items below for each principle.' }, bullets: [
        { ja: '記述: 何を守るのか(一文)', en: 'Statement: what is upheld, one sentence' },
        { ja: '根拠: なぜそうするのか(事業上の理由)', en: 'Rationale: the business reason' },
        { ja: '含意: 何を諦め、何が制約されるのか', en: 'Implications: what is given up and what becomes constrained' },
        { ja: '優先度: 他原則と衝突した場合の扱い', en: 'Precedence: what happens when it conflicts with another principle' },
      ] },
    ],
  },
  {
    id: 'organizational-model',
    name: { ja: 'EA のための組織モデル', en: 'Organizational Model for Enterprise Architecture' },
    summary: {
      ja: 'アーキテクチャを実践する体制を定義する文書。対象範囲、役割と責任、意思決定権限、既存組織との関係、予算と要員を記述する。',
      en: 'Defines the organization that will practise architecture: coverage, roles and responsibilities, decision rights, relationships to existing bodies, budget, and staffing.',
    },
    createdInPhaseIds: ['preliminary'],
    refinedInPhaseIds: ['h'],
    contents: [
      { ja: '対象とする組織範囲と、その外との境界', en: 'Which parts of the enterprise are covered, and the boundary beyond' },
      { ja: '役割と責任(アーキテクト、ボード、スポンサー、実装チーム)', en: 'Roles and responsibilities: architects, board, sponsors, delivery teams' },
      { ja: '意思決定権限と、決定を覆せる者', en: 'Decision rights, and who can overturn a decision' },
      { ja: '既存のガバナンス体制・PMO との関係', en: 'Relationship to existing governance bodies and the PMO' },
      { ja: '要員のスキル要件と充足状況、予算', en: 'Skill requirements, current staffing, and budget' },
    ],
    tips: [
      { ja: '「誰が決定を覆せるか」を書けない組織モデルは、実運用で必ず破綻する。', en: 'An organizational model that cannot say who overturns a decision will break in practice.' },
      { ja: '兼務前提の体制なら、EA 作業に割ける工数の割合まで明記する。', en: 'If roles are part-time, state the percentage of capacity actually available for architecture work.' },
    ],
    keywords: ['organization', '組織', '体制', 'role', '役割', '責任', 'raci', '権限'],
  },
  {
    id: 'tailored-framework',
    name: { ja: 'テーラリング済みフレームワーク', en: 'Tailored Architecture Framework' },
    summary: {
      ja: '自組織向けに調整した ADM と成果物の一式。どのフェーズを使い、どの成果物を作り、どの成果物を作らないかを明示する。既存の開発プロセスや PMO 手続きとの接続点も定義する。',
      en: 'The ADM and deliverable set adjusted for your organization: which phases you use, which deliverables you produce, and which you deliberately skip — plus the connection points to existing delivery processes and PMO procedures.',
    },
    createdInPhaseIds: ['preliminary'],
    refinedInPhaseIds: ['h'],
    contents: [
      { ja: '採用するフェーズと省略するフェーズ、その理由', en: 'Phases adopted, phases skipped, and why' },
      { ja: '作成する成果物一覧と、各成果物のテンプレート', en: 'The deliverable list and the template for each' },
      { ja: '既存プロセス(開発標準、PMO、調達)との接続点', en: 'Connection points to existing processes: delivery standards, PMO, procurement' },
      { ja: '組織固有の用語との対応表', en: 'A mapping to the organization\'s own terminology' },
      { ja: 'レビューのタイミングとゲート基準', en: 'Review timings and gate criteria' },
    ],
    tips: [
      { ja: '用語の読み替え表を必ず作る。「フェーズ B」と言っても社内では通じない。', en: 'Always build the terminology mapping. Nobody internally knows what "Phase B" means.' },
      { ja: '既存の開発プロセスの成果物で代替できるものは代替する。二重に書かせない。', en: 'Where an existing process artifact can serve, use it. Never make people write the same thing twice.' },
    ],
    keywords: ['tailoring', 'テーラリング', 'framework', 'フレームワーク', 'カスタマイズ', '適用'],
  },
  {
    id: 'architecture-vision',
    name: { ja: 'アーキテクチャビジョン', en: 'Architecture Vision' },
    summary: {
      ja: 'フェーズ A の中心的成果物。目指す姿を経営層が理解・判断できる粒度で示す。図 1 枚と数ページの説明で、価値・範囲・大まかな移行像・想定リスクを伝える。',
      en: 'The central deliverable of Phase A. It presents the target at a granularity executives can understand and decide on: one diagram and a few pages covering value, scope, the rough transition, and the anticipated risks.',
    },
    createdInPhaseIds: ['a'],
    refinedInPhaseIds: ['b', 'c', 'd', 'e'],
    contents: [
      { ja: '課題認識と変革の理由', en: 'The problem and the reason to change' },
      { ja: '目指す姿(1 枚の概念図 + 説明)', en: 'The target state: one conceptual diagram plus narrative' },
      { ja: '対象範囲・対象外・前提・制約', en: 'Scope, exclusions, assumptions, constraints' },
      { ja: 'ステークホルダーと主要な関心事', en: 'Stakeholders and their principal concerns' },
      { ja: '期待される事業価値と測定可能な成功条件', en: 'Expected business value and measurable success criteria' },
      { ja: '高レベルのギャップと想定される移行の道筋', en: 'High-level gaps and the anticipated transition path' },
      { ja: '初期リスク評価と変革準備度の所見', en: 'Initial risk assessment and readiness findings' },
    ],
    tips: [
      { ja: '説明資料と本文を分けない。1 つの文書で経営層にもアーキテクトにも通じる粒度を狙う。', en: 'Do not split the deck from the document. Aim for one artifact that works for both executives and architects.' },
      { ja: '目指す姿の図に製品名を書かない。この段階での製品固定は選択肢を殺す。', en: 'Keep product names off the target diagram. Fixing products at this stage kills the option space.' },
      { ja: '「やらないこと」を本文の前半に置く。後半に置くと読まれない。', en: 'Put the "not doing" list in the first half. In the second half it goes unread.' },
    ],
    keywords: ['vision', 'ビジョン', 'アーキテクチャビジョン', 'target', '目指す姿', '将来像', 'phase a'],
    template: [
      { heading: { ja: '1. エグゼクティブサマリ', en: '1. Executive Summary' }, guidance: { ja: '課題・目指す姿・投資判断に必要な要点を 1 ページで。', en: 'Problem, target, and what is needed for the investment decision — one page.' } },
      { heading: { ja: '2. 課題認識と変革の理由', en: '2. Problem Statement and Drivers' }, guidance: { ja: '事業指標・現場の痛み・外部環境の変化。数値を入れる。', en: 'Business metrics, operational pain, external change. Include numbers.' } },
      { heading: { ja: '3. 目指す姿', en: '3. Target State' }, guidance: { ja: '概念図 1 枚 + 説明。製品名は書かない。', en: 'One conceptual diagram plus narrative. No product names.' } },
      { heading: { ja: '4. 対象範囲 / 対象外 / 前提 / 制約', en: '4. Scope / Exclusions / Assumptions / Constraints' }, guidance: { ja: '対象外を明記する。ここが後の変更管理の基準線になる。', en: 'State the exclusions. This becomes the baseline for later change control.' } },
      { heading: { ja: '5. ステークホルダーと関心事', en: '5. Stakeholders and Concerns' }, guidance: { ja: '氏名・役割・関心事・関与方針を表で。', en: 'A table of name, role, concern, and engagement approach.' } },
      { heading: { ja: '6. 期待価値と成功条件', en: '6. Expected Value and Success Criteria' }, guidance: { ja: '測定可能な指標と、測定の担当・時期。', en: 'Measurable indicators, plus who measures them and when.' } },
      { heading: { ja: '7. 高レベルギャップと移行の道筋', en: '7. High-Level Gaps and Transition Path' }, guidance: { ja: '大きな塊で 3〜5 段階。詳細はフェーズ E で。', en: 'Three to five coarse steps. The detail comes in Phase E.' } },
      { heading: { ja: '8. リスクと変革準備度', en: '8. Risks and Transformation Readiness' }, guidance: { ja: '初期リスクと残存リスク、準備度の低い因子。', en: 'Initial and residual risk, plus the weakest readiness factors.' } },
    ],
  },
  {
    id: 'statement-of-architecture-work',
    name: { ja: 'アーキテクチャ作業範囲記述書', en: 'Statement of Architecture Work' },
    summary: {
      ja: 'アーキテクチャ作業そのものの契約書にあたる文書。何を、誰が、いつまでに、どの成果物として作るのかを定義し、スポンサーの承認を得る。以降の作業の権限の根拠になる。',
      en: 'The contract for the architecture work itself: what will be produced, by whom, by when, and as which deliverables — approved by the sponsor. It is the mandate for everything that follows.',
    },
    createdInPhaseIds: ['a'],
    refinedInPhaseIds: ['b', 'c', 'd', 'e', 'f'],
    contents: [
      { ja: '作業の目的と背景', en: 'Purpose and background of the work' },
      { ja: '作業範囲(扱う組織・ドメイン・時間軸・詳細度)', en: 'Scope: organizations, domains, time horizon, level of detail' },
      { ja: '作成する成果物の一覧と受け入れ基準', en: 'The deliverable list and the acceptance criteria for each' },
      { ja: '体制・役割・工数見積り・スケジュール', en: 'Team, roles, effort estimate, and schedule' },
      { ja: '前提・制約・依存関係', en: 'Assumptions, constraints, dependencies' },
      { ja: '承認者と承認日', en: 'Approver and approval date' },
    ],
    tips: [
      { ja: '「詳細度」を明記する。同じ範囲でも詳細度で工数が 5 倍変わる。', en: 'State the level of detail. For the same scope, detail can swing effort by five times.' },
      { ja: '受け入れ基準を成果物ごとに書く。「レビューを通ること」では基準にならない。', en: 'Write acceptance criteria per deliverable. "Passes review" is not a criterion.' },
      { ja: '変更が生じた場合の再承認プロセスを本文に入れておく。', en: 'Include the re-approval process for when scope changes.' },
    ],
    keywords: ['statement of architecture work', 'sow', '作業範囲', '記述書', 'スコープ', '承認', 'phase a'],
    template: [
      { heading: { ja: '1. 目的と背景', en: '1. Purpose and Background' }, guidance: { ja: '作業依頼書の内容を要約し、アーキテクトの理解として書き直す。', en: 'Summarize the request and restate it as the architect\'s understanding.' } },
      { heading: { ja: '2. 作業範囲', en: '2. Scope of Work' }, guidance: { ja: '組織範囲・ドメイン(B/C/D のどこまで)・時間軸・詳細度の 4 軸で書く。', en: 'Four axes: organizational coverage, domains (how far into B/C/D), time horizon, level of detail.' } },
      { heading: { ja: '3. 成果物と受け入れ基準', en: '3. Deliverables and Acceptance Criteria' }, guidance: { ja: '成果物ごとに 1 行の受け入れ基準を書く。', en: 'One line of acceptance criteria per deliverable.' } },
      { heading: { ja: '4. 体制とスケジュール', en: '4. Team and Schedule' }, guidance: { ja: '役割・氏名・稼働率・マイルストーン。', en: 'Role, name, allocation, milestones.' } },
      { heading: { ja: '5. 前提・制約・依存関係', en: '5. Assumptions, Constraints, Dependencies' }, guidance: { ja: '崩れたら計画を見直す前提を明示する。', en: 'Name the assumptions whose failure would force a re-plan.' } },
      { heading: { ja: '6. 変更管理', en: '6. Change Control' }, guidance: { ja: '範囲変更時の再承認の手順と承認者。', en: 'The re-approval procedure and approver for scope changes.' } },
      { heading: { ja: '7. 承認', en: '7. Approval' }, guidance: { ja: 'スポンサー名・役職・承認日。', en: 'Sponsor name, title, approval date.' } },
    ],
  },
  {
    id: 'stakeholder-map',
    name: { ja: 'ステークホルダーマップ', en: 'Stakeholder Map' },
    summary: {
      ja: '関係者・関心事・影響力・関与方針を一覧化した成果物。誰にどのビューを見せるかの設計図でもある。',
      en: 'A catalog of stakeholders, concerns, influence, and engagement approach. It doubles as the design for which view each audience is shown.',
    },
    createdInPhaseIds: ['a'],
    refinedInPhaseIds: ['b', 'c', 'd', 'g', 'h'],
    contents: [
      { ja: '氏名・役職・所属', en: 'Name, title, organization' },
      { ja: '関心事(具体的に。「品質」ではなく「月末処理が止まらないこと」)', en: 'Concerns, stated concretely — not "quality" but "month-end must not stall"' },
      { ja: '影響力と関心度の評価', en: 'Assessed power and interest' },
      { ja: '関与方針と担当アーキテクト', en: 'Engagement approach and the architect who owns the relationship' },
      { ja: '関心事に応えるビュー・成果物', en: 'The view or deliverable that answers each concern' },
    ],
    tips: [
      { ja: '反対者・懐疑派を必ず載せる。載っていないマップは使い物にならない。', en: 'Always include the sceptics and opponents. A map without them is useless.' },
      { ja: '関心事は本人の言葉で引用する。要約すると本質が抜ける。', en: 'Quote concerns in the person\'s own words. Summarizing loses the point.' },
    ],
    keywords: ['stakeholder', 'ステークホルダー', 'マップ', '関心事', 'concerns', '影響力'],
  },
  {
    id: 'communications-plan',
    name: { ja: 'コミュニケーション計画', en: 'Communications Plan' },
    summary: {
      ja: '誰に、何を、いつ、どの形式で伝えるかを定義した計画。EA の成果物は「作ること」ではなく「伝わること」で価値が出るため、この計画の質が成否に直結する。',
      en: 'Defines who is told what, when, and in which format. EA deliverables create value by landing, not by existing, so the quality of this plan drives the outcome.',
    },
    createdInPhaseIds: ['a'],
    refinedInPhaseIds: ['b', 'c', 'd', 'e', 'f', 'g'],
    contents: [
      { ja: '対象者ごとの伝達内容と粒度', en: 'What each audience is told, and at what depth' },
      { ja: '頻度・タイミング(節目、定例)', en: 'Frequency and timing: milestones and regular cadence' },
      { ja: '形式(1 枚資料、ワークショップ、定義書、ダッシュボード)', en: 'Format: one-pager, workshop, definition document, dashboard' },
      { ja: '発信者と承認者', en: 'Who sends it and who approves it' },
      { ja: 'フィードバックの受け口', en: 'Where feedback comes back in' },
    ],
    tips: [
      { ja: '経営層向けは「1 枚 + 3 分」を基準に設計する。', en: 'Design executive communication around "one page, three minutes".' },
      { ja: '悪い知らせほど早く、定例を待たずに伝える経路を作っておく。', en: 'Build a route for bad news that does not wait for the next scheduled meeting.' },
    ],
    keywords: ['communication', 'コミュニケーション', '計画', '報告', '説明', 'レポート'],
  },
  {
    id: 'architecture-definition-document',
    name: { ja: 'アーキテクチャ定義書', en: 'Architecture Definition Document' },
    summary: {
      ja: 'B〜D で作られる中核文書。ビジネス・データ・アプリケーション・テクノロジーの各ドメインについて、現行と目標のアーキテクチャ、およびその差分を記述する。ADD と略される。',
      en: 'The core document produced across Phases B–D. It describes baseline and target architectures — and the delta — for the business, data, application, and technology domains. Commonly abbreviated ADD.',
    },
    createdInPhaseIds: ['b', 'c', 'd'],
    refinedInPhaseIds: ['e', 'f', 'g', 'h'],
    contents: [
      { ja: 'スコープ・前提・制約(作業範囲記述書との整合)', en: 'Scope, assumptions, constraints, consistent with the Statement of Architecture Work' },
      { ja: 'ビジネスアーキテクチャ(現行/目標): 能力、バリューストリーム、プロセス、組織', en: 'Business architecture, baseline and target: capabilities, value streams, processes, organization' },
      { ja: 'データアーキテクチャ(現行/目標): 主要エンティティ、正本、ライフサイクル', en: 'Data architecture, baseline and target: key entities, systems of record, lifecycle' },
      { ja: 'アプリケーションアーキテクチャ(現行/目標): 論理構成要素、機能配置、連携', en: 'Application architecture, baseline and target: logical components, function placement, interfaces' },
      { ja: 'テクノロジーアーキテクチャ(現行/目標): プラットフォーム、配置、運用、セキュリティ', en: 'Technology architecture, baseline and target: platform, placement, operations, security' },
      { ja: 'ドメイン横断のギャップ一覧', en: 'The consolidated cross-domain gap list' },
      { ja: 'ステークホルダー別ビュー', en: 'Views organized by stakeholder' },
    ],
    tips: [
      { ja: '全ドメインを同じ深さで書かない。案件の争点があるドメインを厚く書く。', en: 'Do not write every domain to the same depth. Go deep where the engagement\'s real argument is.' },
      { ja: '図とテキストの重複を避ける。図で伝わることを文章で繰り返すと保守されなくなる。', en: 'Avoid duplicating diagrams in prose. Repeated content stops being maintained.' },
      { ja: '各記述に「誰の関心事に答えているか」を注記すると、不要な章が可視化される。', en: 'Annotate each section with the concern it answers; the unnecessary chapters reveal themselves.' },
    ],
    keywords: ['add', 'architecture definition', 'アーキテクチャ定義書', '定義書', 'baseline', 'target', '現行', '目標'],
    template: [
      { heading: { ja: '1. スコープと前提', en: '1. Scope and Assumptions' }, guidance: { ja: '作業範囲記述書からの引き写しではなく、実作業で確定した範囲を書く。', en: 'Not a copy of the Statement of Architecture Work — the scope as actually settled during the work.' } },
      { heading: { ja: '2. ビジネスアーキテクチャ', en: '2. Business Architecture' }, guidance: { ja: '現行 / 目標 / ギャップ。能力とバリューストリームを軸に。', en: 'Baseline, target, gaps — organized around capabilities and value streams.' } },
      { heading: { ja: '3. データアーキテクチャ', en: '3. Data Architecture' }, guidance: { ja: '主要エンティティと正本システム。CRUD マトリクスを添付。', en: 'Key entities and their system of record. Attach the CRUD matrix.' } },
      { heading: { ja: '4. アプリケーションアーキテクチャ', en: '4. Application Architecture' }, guidance: { ja: '論理構成要素と連携。製品名は物理の節に分ける。', en: 'Logical components and interfaces. Keep product names in the physical section.' } },
      { heading: { ja: '5. テクノロジーアーキテクチャ', en: '5. Technology Architecture' }, guidance: { ja: '非機能要件との対応を明示する。', en: 'Show explicitly how each non-functional requirement is met.' } },
      { heading: { ja: '6. ギャップ一覧', en: '6. Consolidated Gaps' }, guidance: { ja: 'ドメイン横断で統合し、重複を排除した一覧。', en: 'Merged across domains with duplicates removed.' } },
      { heading: { ja: '7. ステークホルダー別ビュー', en: '7. Stakeholder Views' }, guidance: { ja: '関心事 → ビューの対応表を先頭に置く。', en: 'Lead with the concern-to-view mapping table.' } },
    ],
  },
  {
    id: 'architecture-requirements-spec',
    name: { ja: 'アーキテクチャ要件仕様', en: 'Architecture Requirements Specification' },
    summary: {
      ja: 'アーキテクチャが満たすべき要件を、測定可能な形で列挙した文書。要件管理を通じて全フェーズで更新され続ける。実装チームへの受け渡しの中核でもある。',
      en: 'A list of the requirements the architecture must satisfy, stated measurably. It is maintained across every phase through Requirements Management and is the core of the handover to delivery teams.',
    },
    createdInPhaseIds: ['b', 'c', 'd', 'requirements-management'],
    refinedInPhaseIds: ['e', 'f', 'g', 'h'],
    contents: [
      { ja: '要件 ID・出所・提起者', en: 'Requirement ID, source, and who raised it' },
      { ja: '要件記述(検証可能な形で)', en: 'The requirement, stated so it can be verified' },
      { ja: '種別(機能/非機能/制約/規制)と優先度', en: 'Type — functional, non-functional, constraint, regulatory — and priority' },
      { ja: '受け入れ基準・測定方法', en: 'Acceptance criteria and how it will be measured' },
      { ja: '関連する成果物・アーキテクチャ構成要素へのトレース', en: 'Traceability to deliverables and architecture components' },
      { ja: '状態(提案/承認/実装済/却下)', en: 'State: proposed, approved, implemented, rejected' },
    ],
    tips: [
      { ja: '非機能要件には必ず数値と測定条件を書く。「高速に」は要件ではない。', en: 'Non-functional requirements need a number and the conditions of measurement. "Fast" is not a requirement.' },
      { ja: '却下要件も残す。同じ要求が形を変えて再提出されたときに議論を短縮できる。', en: 'Keep rejected requirements. When the same ask returns in new clothes, the debate is much shorter.' },
    ],
    keywords: ['requirements', '要件', '要件仕様', 'specification', '非機能', 'traceability', 'トレーサビリティ'],
  },
  {
    id: 'business-capability-map',
    name: { ja: 'ビジネス能力マップ', en: 'Business Capability Map' },
    summary: {
      ja: '事業が「何をできるか」を階層構造で表した図・一覧。組織やプロセスの変更に影響されにくく、投資の議論の共通言語になる。',
      en: 'A hierarchical view of what the business is able to do. It is stable across reorgs and process change, which makes it a shared language for investment discussions.',
    },
    createdInPhaseIds: ['b'],
    refinedInPhaseIds: ['c', 'e', 'h'],
    contents: [
      { ja: '能力の階層(通常 2〜3 階層)', en: 'The capability hierarchy, usually two or three levels' },
      { ja: '能力ごとの定義(何ができることを指すのか)', en: 'A definition per capability: what being able to do it means' },
      { ja: '能力の責任者', en: 'The owner of each capability' },
      { ja: '現在水準・目標水準の評価', en: 'Current and target maturity ratings' },
      { ja: '能力を支える組織・プロセス・システム・情報の対応', en: 'The organizations, processes, systems, and information that support it' },
    ],
    tips: [
      { ja: '動詞ではなく名詞で書く(「受注する」ではなく「受注管理」)。プロセスとの混同を防げる。', en: 'Name capabilities as nouns, not verbs ("order management", not "take orders"). It prevents confusion with process.' },
      { ja: '色分け(ヒートマップ)は 1 つの軸だけにする。複数軸を同時に塗ると読めない。', en: 'Heat-map on one dimension only. Colouring several at once makes it unreadable.' },
    ],
    keywords: ['capability', '能力', 'ケイパビリティ', 'マップ', 'heatmap', 'ヒートマップ', 'ビジネス'],
  },
  {
    id: 'application-portfolio-catalog',
    name: { ja: 'アプリケーションポートフォリオカタログ', en: 'Application Portfolio Catalog' },
    summary: {
      ja: '組織が保有するアプリケーションの一覧と属性。刷新・統廃合の判断材料であり、フェーズ C の現行分析の土台になる。',
      en: 'The inventory of applications the organization owns, with attributes. It is the evidence base for rationalization decisions and the foundation of baseline analysis in Phase C.',
    },
    createdInPhaseIds: ['c'],
    refinedInPhaseIds: ['d', 'e', 'h'],
    contents: [
      { ja: 'アプリケーション名・業務所管・IT 所管', en: 'Application name, business owner, IT owner' },
      { ja: '支援する業務機能・能力', en: 'The business functions and capabilities it supports' },
      { ja: '利用者数・重要度・稼働環境', en: 'User count, criticality, hosting environment' },
      { ja: '技術構成・サポート期限・保守費用', en: 'Technology stack, support end-of-life, maintenance cost' },
      { ja: '事業価値と技術的健全性の評価(廃止/維持/更改/置換の判定)', en: 'Business value and technical health ratings, leading to a retire / maintain / upgrade / replace verdict' },
    ],
    tips: [
      { ja: '「事業価値 × 技術的健全性」の 2 軸評価まで入れて初めて意思決定に使える。一覧だけでは動かない。', en: 'Only with the two-axis rating — business value against technical health — does the catalog drive decisions. A bare list changes nothing.' },
      { ja: 'シャドー IT を拾うため、部門の経費申請から逆引きすると精度が上がる。', en: 'Cross-check against departmental expense claims to surface shadow IT; accuracy improves markedly.' },
    ],
    keywords: ['application', 'アプリケーション', 'portfolio', 'ポートフォリオ', 'カタログ', 'システム一覧', '棚卸し', '刷新'],
  },
  {
    id: 'data-entity-catalog',
    name: { ja: 'データエンティティカタログ', en: 'Data Entity Catalog' },
    summary: {
      ja: '主要な業務データの一覧と、その正本・利用範囲・管理責任を整理した成果物。マスタデータ統合やデータガバナンスの出発点になる。',
      en: 'A catalog of the key business data entities with their system of record, usage, and stewardship. It is the starting point for master data consolidation and data governance.',
    },
    createdInPhaseIds: ['c'],
    refinedInPhaseIds: ['d', 'e', 'h'],
    contents: [
      { ja: 'エンティティ名と業務上の定義', en: 'Entity name and business definition' },
      { ja: '正本システム(system of record)', en: 'System of record' },
      { ja: 'データ管理責任者(データスチュワード)', en: 'Data steward' },
      { ja: '作成・参照・更新・削除するシステム(CRUD)', en: 'Systems that create, read, update, delete it' },
      { ja: '機密区分・保持期間・規制要件', en: 'Sensitivity classification, retention period, regulatory requirements' },
    ],
    tips: [
      { ja: '定義の食い違いこそが本題。「顧客」の定義が部門ごとに違うことを可視化するだけで価値がある。', en: 'The definitional disagreements are the point. Simply exposing that each unit defines "customer" differently already delivers value.' },
      { ja: '全データを網羅しようとしない。争点になる 20〜30 エンティティで十分。', en: 'Do not aim for completeness. The twenty or thirty contested entities are enough.' },
    ],
    keywords: ['data', 'データ', 'エンティティ', 'entity', 'master data', 'マスタ', 'crud', 'system of record', '正本'],
  },
  {
    id: 'technology-standards-catalog',
    name: { ja: '技術標準カタログ', en: 'Technology Standards Catalog' },
    summary: {
      ja: '組織として認めた技術・製品・バージョンの一覧と、その位置づけ(推奨/許容/非推奨/廃止予定)。技術選定の判断を高速化し、乱立を防ぐ。',
      en: 'The list of technologies, products, and versions the organization sanctions, each with a status: preferred, acceptable, discouraged, or retiring. It speeds technology selection and curbs sprawl.',
    },
    createdInPhaseIds: ['d'],
    refinedInPhaseIds: ['g', 'h'],
    contents: [
      { ja: '技術分類(実行基盤、DB、連携、監視、認証 など)', en: 'Technology category: runtime, database, integration, monitoring, identity, and so on' },
      { ja: '製品・バージョンと位置づけ(推奨/許容/非推奨/廃止予定)', en: 'Product and version with status: preferred, acceptable, discouraged, retiring' },
      { ja: '適用条件と例外の扱い', en: 'Conditions of use and how exceptions are handled' },
      { ja: 'サポート期限と移行先', en: 'Support end date and the migration destination' },
      { ja: '所管部門・問い合わせ先', en: 'Owning team and where to ask' },
    ],
    tips: [
      { ja: '「廃止予定」に必ず移行先を書く。移行先のない廃止予定は無視される。', en: 'Every "retiring" entry needs a destination. Without one it is simply ignored.' },
      { ja: '更新の頻度と責任者を決める。放置された標準カタログは有害。', en: 'Fix the update cadence and owner. A stale standards catalog does active harm.' },
    ],
    keywords: ['technology', '技術標準', 'standards', 'カタログ', '製品', 'version', 'eol', 'サポート期限'],
  },
  {
    id: 'architecture-roadmap',
    name: { ja: 'アーキテクチャロードマップ', en: 'Architecture Roadmap' },
    summary: {
      ja: '現行から目標へ至る道筋を、作業パッケージと中間状態(移行アーキテクチャ)の時系列として表した成果物。フェーズ E で作られ、F で予算と体制が付く。',
      en: 'The path from baseline to target expressed as a timeline of work packages and intermediate states. Produced in Phase E and given budget and staffing in Phase F.',
    },
    createdInPhaseIds: ['e'],
    refinedInPhaseIds: ['f', 'g', 'h'],
    contents: [
      { ja: '作業パッケージ一覧(範囲、成果、規模)', en: 'Work packages with scope, outcome, and size' },
      { ja: '依存関係と実施順序', en: 'Dependencies and sequence' },
      { ja: '移行アーキテクチャ(中間状態)とその到達時期', en: 'Transition architectures and when each is reached' },
      { ja: '各段階で実現される事業価値', en: 'The business value realized at each step' },
      { ja: '前提・制約(予算サイクル、規制期日、要員)', en: 'Assumptions and constraints: budget cycle, regulatory dates, staffing' },
    ],
    tips: [
      { ja: '横軸を「四半期」にする。月単位は精度を装った嘘になり、年単位は判断に使えない。', en: 'Use quarters on the horizontal axis. Months fake a precision you do not have; years are useless for deciding.' },
      { ja: '各中間状態に「ここで止めても事業は回るか」の欄を作る。', en: 'Give every intermediate state a column: "can we stop here and still operate?"' },
    ],
    keywords: ['roadmap', 'ロードマップ', '計画', 'work package', '作業パッケージ', 'transition', '移行', '順序'],
    template: [
      { heading: { ja: '1. 前提と制約', en: '1. Assumptions and Constraints' }, guidance: { ja: '予算サイクル・規制期日・要員の空きを先に書く。', en: 'Lead with budget cycle, regulatory dates, and staff availability.' } },
      { heading: { ja: '2. 作業パッケージ一覧', en: '2. Work Packages' }, guidance: { ja: 'ID・名称・範囲・成果・規模・担当を表で。1 パッケージ 3〜6 か月を目安に。', en: 'A table of ID, name, scope, outcome, size, owner. Target three to six months each.' } },
      { heading: { ja: '3. 依存関係', en: '3. Dependencies' }, guidance: { ja: '技術依存だけでなく、予算・要員・組織の依存も書く。', en: 'Not only technical dependencies — budget, staffing, and organizational ones too.' } },
      { heading: { ja: '4. 移行アーキテクチャ(中間状態)', en: '4. Transition Architectures' }, guidance: { ja: '各状態: 到達時期 / 実現する能力 / ここで止めた場合の評価。', en: 'Per state: date reached, capability delivered, and what happens if you stop there.' } },
      { heading: { ja: '5. タイムライン', en: '5. Timeline' }, guidance: { ja: '四半期を横軸に。パッケージと中間状態を重ねて表示。', en: 'Quarters across the top, with packages and transition states overlaid.' } },
      { heading: { ja: '6. 各段階の事業価値', en: '6. Value at Each Step' }, guidance: { ja: '便益・測定指標・便益責任者。', en: 'Benefit, measure, and the person accountable for harvesting it.' } },
    ],
  },
  {
    id: 'transition-architecture',
    name: { ja: '移行アーキテクチャ', en: 'Transition Architecture' },
    summary: {
      ja: '現行と目標の間に置く、実際に到達・運用される中間状態のアーキテクチャ。各中間状態は単独で事業価値を出し、そこで止まっても運用できる必要がある。',
      en: 'An intermediate architecture that is actually reached and operated between baseline and target. Each one must deliver business value on its own and remain operable if the programme stops there.',
    },
    createdInPhaseIds: ['e'],
    refinedInPhaseIds: ['f', 'g'],
    contents: [
      { ja: 'その状態で実現している能力・機能', en: 'The capabilities and functions in place at that state' },
      { ja: '残っている現行構成要素と、共存のための仕組み', en: 'Which baseline components remain and how coexistence is handled' },
      { ja: 'その状態で発生する一時的な仕組み(暫定連携、二重運用)', en: 'Temporary machinery at that state: interim interfaces, dual running' },
      { ja: '到達条件と次の状態への移行条件', en: 'Entry criteria and the criteria for moving to the next state' },
      { ja: '一時的な仕組みの廃棄計画', en: 'The disposal plan for the temporary machinery' },
    ],
    tips: [
      { ja: '暫定の仕組みには必ず廃棄計画と期限を付ける。暫定が恒久化するのは、期限を書かなかったから。', en: 'Every interim mechanism needs a disposal plan and a date. Interim things become permanent precisely because no date was written.' },
      { ja: '二重運用の期間中のコストを見積もる。ここを過小評価した移行計画は必ず遅れる。', en: 'Estimate the cost of the dual-running period. Migration plans that understate it always slip.' },
    ],
    keywords: ['transition', '移行アーキテクチャ', '中間状態', 'interim', '暫定', '共存', '二重運用'],
  },
  {
    id: 'implementation-migration-plan',
    name: { ja: '実装移行計画', en: 'Implementation and Migration Plan' },
    summary: {
      ja: 'ロードマップに予算・体制・スケジュール・受け入れ基準を付けた実行計画。フェーズ F で完成し、既存のポートフォリオ/プロジェクト管理へ引き渡される。',
      en: 'The roadmap with budget, staffing, schedule, and acceptance criteria attached. Completed in Phase F and handed over to the existing portfolio and project management processes.',
    },
    createdInPhaseIds: ['f'],
    refinedInPhaseIds: ['g', 'h'],
    contents: [
      { ja: 'プロジェクト分割と実施順序', en: 'Breakdown into projects and their sequence' },
      { ja: 'コスト見積りと予算配分(年度別)', en: 'Cost estimates and budget allocation by fiscal year' },
      { ja: '便益と便益責任者、測定時期', en: 'Benefits, benefit owners, and when they are measured' },
      { ja: '体制・要員計画・必要スキル', en: 'Team structure, staffing plan, required skills' },
      { ja: 'マイルストーンと受け入れ基準', en: 'Milestones and acceptance criteria' },
      { ja: 'リスクと緩和策、残存リスクの受容者', en: 'Risks, mitigations, and who accepts the residual risk' },
      { ja: 'ガバナンス(レビュー時期、判断ポイント)', en: 'Governance: review points and decision gates' },
    ],
    tips: [
      { ja: '会計年度をまたぐ大きな塊は、年度内で完結する単位に割る。', en: 'Break anything that straddles fiscal years into units that complete within one.' },
      { ja: '中止判断のポイント(kill point)を計画に明記する。止められない計画は暴走する。', en: 'Write the kill points into the plan. A plan that cannot be stopped will run away.' },
    ],
    keywords: ['implementation', '実装', 'migration plan', '移行計画', '実行計画', '予算', 'budget', 'schedule', 'スケジュール'],
    template: [
      { heading: { ja: '1. 計画の前提', en: '1. Planning Assumptions' }, guidance: { ja: 'ロードマップからの変更点と、その理由。', en: 'What changed from the roadmap, and why.' } },
      { heading: { ja: '2. プロジェクト分割と順序', en: '2. Project Breakdown and Sequence' }, guidance: { ja: '年度内に完結する単位に割る。', en: 'Break into units that complete within a fiscal year.' } },
      { heading: { ja: '3. コストと予算配分', en: '3. Cost and Budget Allocation' }, guidance: { ja: '年度別・費目別。運用費の増分も忘れず入れる。', en: 'By year and category. Do not forget the increase in run cost.' } },
      { heading: { ja: '4. 便益と測定', en: '4. Benefits and Measurement' }, guidance: { ja: '便益 / 指標 / 便益責任者 / 測定時期 の 4 列。', en: 'Four columns: benefit, measure, benefit owner, measurement date.' } },
      { heading: { ja: '5. 体制と要員', en: '5. Team and Staffing' }, guidance: { ja: '必要スキルと、その充足手段(採用/育成/調達)。', en: 'Required skills and how they are met: hire, train, or contract.' } },
      { heading: { ja: '6. マイルストーンと受け入れ基準', en: '6. Milestones and Acceptance Criteria' }, guidance: { ja: '中止判断ポイント(kill point)を必ず入れる。', en: 'Include the kill points.' } },
      { heading: { ja: '7. リスクと残存リスク', en: '7. Risks and Residual Risk' }, guidance: { ja: '受容者は個人名で記載する。', en: 'Name a person as the acceptor.' } },
      { heading: { ja: '8. ガバナンスと引き渡し', en: '8. Governance and Handover' }, guidance: { ja: 'PMO との受け入れ基準の合意を含める。', en: 'Include the acceptance criteria agreed with the PMO.' } },
    ],
  },
  {
    id: 'architecture-contract',
    name: { ja: 'アーキテクチャ契約', en: 'Architecture Contract' },
    summary: {
      ja: 'アーキテクチャ機能と実装チーム(または供給者)の間で、守るべきアーキテクチャ上の取り決めを合意する文書。フェーズ G のガバナンスの実効性はこの契約の有無で決まる。',
      en: 'The agreement between the architecture function and the delivery team or supplier on the architectural commitments to be honoured. Whether Phase G governance has teeth depends on whether this exists.',
    },
    createdInPhaseIds: ['f', 'g'],
    refinedInPhaseIds: ['g', 'h'],
    contents: [
      { ja: '当事者と適用範囲', en: 'Parties and scope of application' },
      { ja: '遵守すべきアーキテクチャ要件・原則・標準', en: 'Architecture requirements, principles, and standards to be honoured' },
      { ja: 'レビューのタイミングと通過基準', en: 'Review points and pass criteria' },
      { ja: '適合性の測定方法と報告義務', en: 'How conformance is measured and the reporting obligations' },
      { ja: '例外申請の手順と承認者', en: 'The exception procedure and who approves' },
      { ja: '不適合時の扱い(是正、エスカレーション)', en: 'What happens on non-conformance: remediation and escalation' },
    ],
    tips: [
      { ja: '外部ベンダー案件では調達契約に組み込む。付属文書のままでは効力が薄い。', en: 'On vendor engagements, fold it into the procurement contract. Left as an annex it carries little weight.' },
      { ja: '守れない条項を入れない。1 つでも死文化すると契約全体が軽く扱われる。', en: 'Do not include clauses you will not enforce. One dead clause devalues the whole contract.' },
    ],
    keywords: ['contract', '契約', 'アーキテクチャ契約', 'ベンダー', 'vendor', '遵守', 'compliance', '調達'],
  },
  {
    id: 'compliance-assessment',
    name: { ja: 'アーキテクチャ適合性評価', en: 'Architecture Compliance Assessment' },
    summary: {
      ja: '実装がアーキテクチャに沿っているかを評価した記録。準拠の度合いを段階で判定し、逸脱については是正か例外承認かを決める。',
      en: 'The record of how far an implementation follows the architecture. Conformance is rated on a scale, and each deviation is resolved as either remediation or a granted exception.',
    },
    createdInPhaseIds: ['g'],
    refinedInPhaseIds: ['h'],
    contents: [
      { ja: '評価対象(プロジェクト、システム、時点)', en: 'What was assessed: project, system, point in time' },
      { ja: '評価項目と判定(準拠/一部準拠/非準拠/非適合)', en: 'Criteria and rating: conformant, partially conformant, non-conformant, irreconcilable' },
      { ja: '逸脱の内容と理由', en: 'The deviations and the reasons behind them' },
      { ja: '是正計画または例外承認(期限付き)', en: 'Remediation plan or granted exception, with an expiry date' },
      { ja: '次回評価の時期', en: 'The date of the next assessment' },
    ],
    tips: [
      { ja: '逸脱の「理由」を必ず記録する。理由の集計がアーキテクチャ改善の最良の材料になる。', en: 'Always record why a deviation happened. Aggregated reasons are the best input to improving the architecture itself.' },
      { ja: '評価は設計段階で行う。実装完了後の評価は、指摘しても直せない。', en: 'Assess at design time. Findings after implementation cannot be acted on.' },
    ],
    keywords: ['compliance', '適合性', '準拠', 'assessment', '評価', 'レビュー', '逸脱', 'deviation'],
  },
  {
    id: 'requirements-impact-assessment',
    name: { ja: '要件影響評価', en: 'Requirements Impact Assessment' },
    summary: {
      ja: '要件の新規追加・変更が、どのフェーズ・成果物・実装に影響するかを評価した記録。要件管理の中核成果物であり、再作業の要否判断の根拠になる。',
      en: 'The record of which phases, deliverables, and implementations a new or changed requirement affects. It is the core artifact of Requirements Management and the basis for deciding whether rework is needed.',
    },
    createdInPhaseIds: ['requirements-management'],
    refinedInPhaseIds: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    contents: [
      { ja: '対象要件 ID と変更内容', en: 'The requirement ID and what changed' },
      { ja: '影響を受けるフェーズ・成果物・アーキテクチャ構成要素', en: 'Affected phases, deliverables, and architecture components' },
      { ja: '影響の大きさ(工数、スケジュール、コスト)', en: 'Size of impact: effort, schedule, cost' },
      { ja: '再作業の要否と、差し戻し先フェーズ', en: 'Whether rework is required and which phase it goes back to' },
      { ja: '判断と承認者', en: 'The decision and who approved it' },
    ],
    tips: [
      { ja: '「影響なし」と判断した場合もその判断を記録する。後で問題になったときの根拠になる。', en: 'Record "no impact" verdicts too. They are your evidence when it later turns out otherwise.' },
      { ja: '影響評価を省略した変更が、後工程で最も高くつく。', en: 'The changes that skip impact assessment are the ones that cost the most downstream.' },
    ],
    keywords: ['requirements', '要件', '影響評価', 'impact', '変更', 'change', '再作業', 'rework'],
  },
  {
    id: 'architecture-repository',
    name: { ja: 'アーキテクチャリポジトリ', en: 'Architecture Repository' },
    summary: {
      ja: 'アーキテクチャ成果物・標準・参照モデル・決定記録を保管し、再利用可能にする仕組み。個々の成果物ではなく「資産の蓄積」を扱う点が特徴。',
      en: 'The store that holds architecture deliverables, standards, reference models, and decision records, and makes them reusable. Its subject is the accumulating asset base rather than any single deliverable.',
    },
    createdInPhaseIds: ['preliminary'],
    refinedInPhaseIds: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    contents: [
      { ja: '現行・目標のアーキテクチャ記述', en: 'Baseline and target architecture descriptions' },
      { ja: '標準情報(技術標準、規制、データ定義)', en: 'Standards information: technology standards, regulations, data definitions' },
      { ja: '参照モデル・再利用可能な構成要素', en: 'Reference models and reusable building blocks' },
      { ja: 'ガバナンス記録(決定ログ、例外台帳、適合性評価)', en: 'Governance records: decision log, exception register, compliance assessments' },
      { ja: '版管理と公開範囲', en: 'Versioning and access scope' },
    ],
    tips: [
      { ja: '検索できないリポジトリは存在しないのと同じ。命名規則と索引を先に決める。', en: 'A repository you cannot search does not exist. Decide naming conventions and the index first.' },
      { ja: '専用ツールにこだわらない。既存のドキュメント基盤 + 明確な構造で十分機能する。', en: 'Do not hold out for a dedicated tool. An existing document platform plus a clear structure works well enough.' },
      { ja: '決定ログ(なぜそう決めたか)が最も再利用される資産になる。', en: 'The decision log — why things were decided — turns out to be the most reused asset of all.' },
    ],
    keywords: ['repository', 'リポジトリ', '資産', 'asset', '再利用', 'reuse', '決定ログ', 'decision log'],
  },
];

export function findDeliverable(id: string): Deliverable | undefined {
  const key = id.trim().toLowerCase();
  return (
    DELIVERABLES.find((d) => d.id === key) ??
    DELIVERABLES.find((d) => d.name.en.toLowerCase() === key || d.name.ja === id.trim())
  );
}
