/**
 * 成果物の知識ベース / Deliverables knowledge base.
 * 独自の要約・実務解説。原文の転載はしない。
 */

import type { Deliverable } from './types.js';

export const DELIVERABLES: Deliverable[] = [
  {
    id: 'request-for-architecture-work',
    name: { ja: 'アーキテクチャ作業依頼書', en: 'Request for Architecture Work' },
    summary: {
      ja: 'アーキテクチャ作業を開始する引き金となる文書。スポンサー側が「何を、なぜ、いつまでに検討してほしいのか」を記述する。ADM サイクルの起点であり、フェーズ H から次サイクルを起動する際にも使う。',
      en: 'The document that triggers architecture work. The sponsoring side states what should be examined, why, and by when. It starts an ADM cycle — including the next cycle raised out of Phase H.',
    },
    createdInPhaseIds: ['preliminary', 'h'],
    refinedInPhaseIds: ['a'],
    contents: [
      { ja: '依頼元組織・スポンサー・責任者', en: 'Requesting organization, sponsor, and accountable executive' },
      { ja: '事業上の背景・課題・変革の動機', en: 'Business context, problem, and the motivation to change' },
      { ja: '検討してほしい範囲と、明示的に対象外とする範囲', en: 'Scope to be examined and what is explicitly excluded' },
      { ja: '既知の制約(予算、期限、規制、既存契約)', en: 'Known constraints: budget, deadline, regulation, existing contracts' },
      { ja: '期待する成果と成功条件', en: 'Expected outcomes and success criteria' },
      { ja: '関連する既存の取り組み・進行中プロジェクト', en: 'Related initiatives and in-flight projects' },
    ],
    tips: [
      { ja: '依頼書が来ないまま作業が始まる案件は多い。その場合はアーキテクト側で草案を書き、スポンサーに承認させるのが現実的。', en: 'Work often starts without one. The practical move is to draft it yourself and have the sponsor approve it.' },
      { ja: '「解決策」が依頼書に書かれていたら、それを要求ではなく仮説として扱う。', en: 'If a solution is already named in the request, treat it as a hypothesis, not a requirement.' },
    ],
    keywords: ['request', '依頼書', 'raw', 'architecture work', '起点', 'トリガー', '作業依頼'],
    template: [
      { heading: { ja: '1. 依頼の概要', en: '1. Request Summary' }, guidance: { ja: '誰が、何を、なぜ依頼するのかを 3〜5 行で。', en: 'Who is asking for what, and why, in three to five lines.' } },
      { heading: { ja: '2. 事業上の背景と課題', en: '2. Business Context and Problem' }, guidance: { ja: '事業指標・現場の痛み・外部環境の変化を具体的に書く。', en: 'Business metrics, operational pain, and external change — concretely.' } },
      { heading: { ja: '3. 対象範囲 / 対象外', en: '3. In Scope / Out of Scope' }, guidance: { ja: '対象外を書くことが最大のリスク対策。', en: 'Writing the out-of-scope list is the strongest risk control here.' } },
      { heading: { ja: '4. 制約と前提', en: '4. Constraints and Assumptions' }, guidance: { ja: '予算・期限・規制・既存契約・技術標準。', en: 'Budget, deadline, regulation, contracts, technology standards.' } },
      { heading: { ja: '5. 期待成果と成功条件', en: '5. Expected Outcomes and Success Criteria' }, guidance: { ja: '測定可能な数値で書く。', en: 'Write measurable numbers.' } },
      { heading: { ja: '6. スポンサーと承認', en: '6. Sponsor and Approval' }, guidance: { ja: 'スポンサーは 1 名。承認日を記録する。', en: 'A single named sponsor. Record the approval date.' } },
    ],
  },
  {
    id: 'architecture-principles',
    name: { ja: 'アーキテクチャ原則', en: 'Architecture Principles' },
    summary: {
      ja: '組織として合意した、アーキテクチャ判断の基準。各原則を「名称・記述・根拠・含意」の 4 点で記述する。レビューや技術選定で実際に参照されて初めて価値が出る。',
      en: 'The agreed criteria for architecture decisions, each written as name, statement, rationale, and implications. They only pay off once they are actually cited in reviews and technology selections.',
    },
    createdInPhaseIds: ['preliminary'],
    refinedInPhaseIds: ['a', 'g', 'h'],
    contents: [
      { ja: '原則の名称(短く、記憶できるもの)', en: 'Principle name — short and memorable' },
      { ja: '記述(何を守るのかを一文で)', en: 'Statement — what is to be upheld, in one sentence' },
      { ja: '根拠(なぜそうするのか、事業上の理由)', en: 'Rationale — the business reason' },
      { ja: '含意(守ることで生じる制約・コスト・諦めるもの)', en: 'Implications — the constraints, costs, and trade-offs of honouring it' },
      { ja: '原則間の優先順位', en: 'Precedence between principles' },
    ],
    tips: [
      { ja: '含意を書けない原則は、まだ原則になっていない。', en: 'If you cannot write the implications, it is not yet a principle.' },
      { ja: '8 個前後に絞る。数を増やすほど拘束力が下がる。', en: 'Aim for around eight. The more you add, the less binding any of them are.' },
    ],
    keywords: ['principle', '原則', 'アーキテクチャ原則', '判断基準', 'rationale', 'implications'],
    template: [
      { heading: { ja: '原則 N: <名称>', en: 'Principle N: <name>' }, guidance: { ja: '以下の 4 項目を各原則ごとに繰り返す。', en: 'Repeat the four items below for each principle.' }, bullets: [
        { ja: '記述: 何を守るのか(一文)', en: 'Statement: what is upheld, one sentence' },
        { ja: '根拠: なぜそうするのか(事業上の理由)', en: 'Rationale: the business reason' },
        { ja: '含意: 何を諦め、何が制約されるのか', en: 'Implications: what is given up and what becomes constrained' },
        { ja: '優先度: 他原則と衝突した場合の扱い', en: 'Precedence: what happens when it conflicts with another principle' },
      ] },
    ],
  },
  {
    id: 'organizational-model',
    name: { ja: 'EA のための組織モデル', en: 'Organizational Model for Enterprise Architecture' },
    summary: {
      ja: 'アーキテクチャを実践する体制を定義する文書。対象範囲、役割と責任、意思決定権限、既存組織との関係、予算と要員を記述する。',
      en: 'Defines the organization that will practise architecture: coverage, roles and responsibilities, decision rights, relationships to existing bodies, budget, and staffing.',
    },
    createdInPhaseIds: ['preliminary'],
    refinedInPhaseIds: ['h'],
    contents: [
      { ja: '対象とする組織範囲と、その外との境界', en: 'Which parts of the enterprise are covered, and the boundary beyond' },
      { ja: '役割と責任(アーキテクト、ボード、スポンサー、実装チーム)', en: 'Roles and responsibilities: architects, board, sponsors, delivery teams' },
      { ja: '意思決定権限と、決定を覆せる者', en: 'Decision rights, and who can overturn a decision' },
      { ja: '既存のガバナンス体制・PMO との関係', en: 'Relationship to existing governance bodies and the PMO' },
      { ja: '要員のスキル要件と充足状況、予算', en: 'Skill requirements, current staffing, and budget' },
    ],
    tips: [
      { ja: '「誰が決定を覆せるか」を書けない組織モデルは、実運用で必ず破綻する。', en: 'An organizational model that cannot say who overturns a decision will break in practice.' },
      { ja: '兼務前提の体制なら、EA 作業に割ける工数の割合まで明記する。', en: 'If roles are part-time, state the percentage of capacity actually available for architecture work.' },
    ],
    keywords: ['organization', '組織', '体制', 'role', '役割', '責任', 'raci', '権限'],
    template: [
      { heading: { ja: '1. 対象範囲と境界', en: '1. Coverage and Boundary' }, guidance: { ja: 'EA が責任を持つ組織・事業・システムの範囲と、その外側を明記する。境界を曖昧にすると「誰の担当でもない領域」が必ず生まれる。', en: 'State which organizations, business units, and systems the EA function owns, and what lies outside. A blurred boundary reliably produces territory nobody owns.' } },
      { heading: { ja: '2. 役割と責任', en: '2. Roles and Responsibilities' }, guidance: { ja: '役割 / 担当者 / 責任範囲 / 稼働率 の 4 列の表で。兼務なら EA 作業に割ける割合まで書く。', en: 'A four-column table: role, person, responsibility, allocation. For part-time roles, state the share of capacity actually available for architecture work.' } },
      { heading: { ja: '3. 意思決定権限', en: '3. Decision Rights' }, guidance: { ja: '決定の種類ごとに、決める人・相談する人・覆せる人を書く。「覆せる人」の欄が空のまま運用を始めると、最初の対立で体制が崩れる。', en: 'Per decision type: who decides, who is consulted, who can overturn. Going live with the "who can overturn" column empty means the first real conflict breaks the model.' } },
      { heading: { ja: '4. 既存ガバナンスとの関係', en: '4. Relationship to Existing Governance' }, guidance: { ja: 'PMO・投資委員会・情報セキュリティ委員会との接続点と、重複する審議をどう整理するか。', en: 'Connection points to the PMO, investment board, and security committee — and how overlapping reviews are deduplicated.' } },
      { heading: { ja: '5. 要員とスキル', en: '5. Staffing and Skills' }, guidance: { ja: '必要スキルと現状の充足度、不足分の埋め方(採用 / 育成 / 外部調達)を書く。', en: 'Required skills against current coverage, and how each gap is closed: hire, develop, or contract.' } },
      { heading: { ja: '6. 予算と予算保有者', en: '6. Budget and Budget Holder' }, guidance: { ja: 'EA 機能の運営費(人件費・ツール・外部調達)と、その予算をどの組織が持つかを書く。予算保有者が決まっていない体制は最初の四半期で止まる。', en: 'The running cost of the EA function — people, tooling, external sourcing — and which organization holds that budget. A function with no named budget holder stalls in its first quarter.' } },
      { heading: { ja: '7. 有効性の測り方', en: '7. How Effectiveness Is Measured' }, guidance: { ja: 'EA 機能自体を何で評価するかを先に決める。決めなければ「作った文書の数」で評価される。', en: 'Decide up front how the EA function itself is judged. Leave it open and it will be judged by document count.' } },
    ],
  },
  {
    id: 'tailored-framework',
    name: { ja: 'テーラリング済みフレームワーク', en: 'Tailored Architecture Framework' },
    summary: {
      ja: '自組織向けに調整した ADM と成果物の一式。どのフェーズを使い、どの成果物を作り、どの成果物を作らないかを明示する。既存の開発プロセスや PMO 手続きとの接続点も定義する。',
      en: 'The ADM and deliverable set adjusted for your organization: which phases you use, which deliverables you produce, and which you deliberately skip — plus the connection points to existing delivery processes and PMO procedures.',
    },
    createdInPhaseIds: ['preliminary'],
    refinedInPhaseIds: ['h'],
    contents: [
      { ja: '採用するフェーズと省略するフェーズ、その理由', en: 'Phases adopted, phases skipped, and why' },
      { ja: '作成する成果物一覧と、各成果物のテンプレート', en: 'The deliverable list and the template for each' },
      { ja: '既存プロセス(開発標準、PMO、調達)との接続点', en: 'Connection points to existing processes: delivery standards, PMO, procurement' },
      { ja: '組織固有の用語との対応表', en: 'A mapping to the organization\'s own terminology' },
      { ja: 'レビューのタイミングとゲート基準', en: 'Review timings and gate criteria' },
    ],
    tips: [
      { ja: '用語の読み替え表を必ず作る。「フェーズ B」と言っても社内では通じない。', en: 'Always build the terminology mapping. Nobody internally knows what "Phase B" means.' },
      { ja: '既存の開発プロセスの成果物で代替できるものは代替する。二重に書かせない。', en: 'Where an existing process artifact can serve, use it. Never make people write the same thing twice.' },
    ],
    keywords: ['tailoring', 'テーラリング', 'framework', 'フレームワーク', 'カスタマイズ', '適用'],
    template: [
      { heading: { ja: '1. テーラリングの方針', en: '1. Tailoring Rationale' }, guidance: { ja: 'なぜ標準のまま使わないのかを 5 行程度で。組織の成熟度・案件規模・既存プロセスの前提を書く。', en: 'In about five lines, why the standard is not used as-is: organizational maturity, typical engagement size, and the existing process landscape.' } },
      { heading: { ja: '2. 採用フェーズと省略フェーズ', en: '2. Phases Adopted and Skipped' }, guidance: { ja: 'フェーズ / 採否 / 理由 / 代替手段 の 4 列の表で。省略の理由を書かないと、後で単なる手抜きと見なされる。', en: 'A four-column table: phase, adopted or not, reason, substitute. Without the reason, a skip later reads as a shortcut.' } },
      { heading: { ja: '3. 作成する成果物と省略する成果物', en: '3. Deliverables Produced and Dropped' }, guidance: { ja: '既存プロセスの文書で代替できるものは代替先を明記する。同じ内容を二度書かせた瞬間に運用は形骸化する。', en: 'Where an existing process document can serve, name it. The moment people write the same content twice, the process is already dead.' } },
      { heading: { ja: '4. 用語の読み替え表', en: '4. Terminology Mapping' }, guidance: { ja: '標準用語 / 社内用語 の対応表。「フェーズ B」と言っても社内では通じない。', en: 'A standard-term to in-house-term table. Nobody internally knows what "Phase B" means.' } },
      { heading: { ja: '5. 既存プロセスとの接続点', en: '5. Integration Points with Existing Processes' }, guidance: { ja: '開発標準・PMO ゲート・調達手続きのどこにアーキテクチャ作業が入るか、その入力と出力を書く。', en: 'Where architecture work plugs into delivery standards, PMO gates, and procurement — with the inputs and outputs at each point.' } },
      { heading: { ja: '6. レビューとゲート基準', en: '6. Reviews and Gate Criteria' }, guidance: { ja: 'いつ・誰が・何を見て通すか。通過基準を書かないゲートは、押印だけの会議になる。', en: 'When, by whom, against what. A gate with no pass criteria degenerates into a rubber-stamp meeting.' } },
      { heading: { ja: '7. 案件規模別の適用の粒度', en: '7. Scaling by Engagement Size' }, guidance: { ja: '大 / 中 / 小の 3 段階で、どこまで簡略化してよいかを決める。全案件にフルセットを求めれば、結局誰も従わない。', en: 'Define how far the process may be trimmed for large, medium, and small engagements. Demand the full set everywhere and nobody follows any of it.' } },
    ],
  },
  {
    id: 'architecture-vision',
    name: { ja: 'アーキテクチャビジョン', en: 'Architecture Vision' },
    summary: {
      ja: 'フェーズ A の中心的成果物。目指す姿を経営層が理解・判断できる粒度で示す。図 1 枚と数ページの説明で、価値・範囲・大まかな移行像・想定リスクを伝える。',
      en: 'The central deliverable of Phase A. It presents the target at a granularity executives can understand and decide on: one diagram and a few pages covering value, scope, the rough transition, and the anticipated risks.',
    },
    createdInPhaseIds: ['a'],
    refinedInPhaseIds: ['b', 'c', 'd', 'e'],
    contents: [
      { ja: '課題認識と変革の理由', en: 'The problem and the reason to change' },
      { ja: '目指す姿(1 枚の概念図 + 説明)', en: 'The target state: one conceptual diagram plus narrative' },
      { ja: '対象範囲・対象外・前提・制約', en: 'Scope, exclusions, assumptions, constraints' },
      { ja: 'ステークホルダーと主要な関心事', en: 'Stakeholders and their principal concerns' },
      { ja: '期待される事業価値と測定可能な成功条件', en: 'Expected business value and measurable success criteria' },
      { ja: '高レベルのギャップと想定される移行の道筋', en: 'High-level gaps and the anticipated transition path' },
      { ja: '初期リスク評価と変革準備度の所見', en: 'Initial risk assessment and readiness findings' },
    ],
    tips: [
      { ja: '説明資料と本文を分けない。1 つの文書で経営層にもアーキテクトにも通じる粒度を狙う。', en: 'Do not split the deck from the document. Aim for one artifact that works for both executives and architects.' },
      { ja: '目指す姿の図に製品名を書かない。この段階での製品固定は選択肢を殺す。', en: 'Keep product names off the target diagram. Fixing products at this stage kills the option space.' },
      { ja: '「やらないこと」を本文の前半に置く。後半に置くと読まれない。', en: 'Put the "not doing" list in the first half. In the second half it goes unread.' },
    ],
    keywords: ['vision', 'ビジョン', 'アーキテクチャビジョン', 'target', '目指す姿', '将来像', 'phase a'],
    template: [
      { heading: { ja: '1. エグゼクティブサマリ', en: '1. Executive Summary' }, guidance: { ja: '課題・目指す姿・投資判断に必要な要点を 1 ページで。', en: 'Problem, target, and what is needed for the investment decision — one page.' } },
      { heading: { ja: '2. 課題認識と変革の理由', en: '2. Problem Statement and Drivers' }, guidance: { ja: '事業指標・現場の痛み・外部環境の変化。数値を入れる。', en: 'Business metrics, operational pain, external change. Include numbers.' } },
      { heading: { ja: '3. 目指す姿', en: '3. Target State' }, guidance: { ja: '概念図 1 枚 + 説明。製品名は書かない。', en: 'One conceptual diagram plus narrative. No product names.' } },
      { heading: { ja: '4. 対象範囲 / 対象外 / 前提 / 制約', en: '4. Scope / Exclusions / Assumptions / Constraints' }, guidance: { ja: '対象外を明記する。ここが後の変更管理の基準線になる。', en: 'State the exclusions. This becomes the baseline for later change control.' } },
      { heading: { ja: '5. ステークホルダーと関心事', en: '5. Stakeholders and Concerns' }, guidance: { ja: '氏名・役割・関心事・関与方針を表で。', en: 'A table of name, role, concern, and engagement approach.' } },
      { heading: { ja: '6. 期待価値と成功条件', en: '6. Expected Value and Success Criteria' }, guidance: { ja: '測定可能な指標と、測定の担当・時期。', en: 'Measurable indicators, plus who measures them and when.' } },
      { heading: { ja: '7. 高レベルギャップと移行の道筋', en: '7. High-Level Gaps and Transition Path' }, guidance: { ja: '大きな塊で 3〜5 段階。詳細はフェーズ E で。', en: 'Three to five coarse steps. The detail comes in Phase E.' } },
      { heading: { ja: '8. リスクと変革準備度', en: '8. Risks and Transformation Readiness' }, guidance: { ja: '初期リスクと残存リスク、準備度の低い因子。', en: 'Initial and residual risk, plus the weakest readiness factors.' } },
    ],
  },
  {
    id: 'statement-of-architecture-work',
    name: { ja: 'アーキテクチャ作業範囲記述書', en: 'Statement of Architecture Work' },
    summary: {
      ja: 'アーキテクチャ作業そのものの契約書にあたる文書。何を、誰が、いつまでに、どの成果物として作るのかを定義し、スポンサーの承認を得る。以降の作業の権限の根拠になる。',
      en: 'The contract for the architecture work itself: what will be produced, by whom, by when, and as which deliverables — approved by the sponsor. It is the mandate for everything that follows.',
    },
    createdInPhaseIds: ['a'],
    refinedInPhaseIds: ['b', 'c', 'd', 'e', 'f'],
    contents: [
      { ja: '作業の目的と背景', en: 'Purpose and background of the work' },
      { ja: '作業範囲(扱う組織・ドメイン・時間軸・詳細度)', en: 'Scope: organizations, domains, time horizon, level of detail' },
      { ja: '作成する成果物の一覧と受け入れ基準', en: 'The deliverable list and the acceptance criteria for each' },
      { ja: '体制・役割・工数見積り・スケジュール', en: 'Team, roles, effort estimate, and schedule' },
      { ja: '前提・制約・依存関係', en: 'Assumptions, constraints, dependencies' },
      { ja: '承認者と承認日', en: 'Approver and approval date' },
    ],
    tips: [
      { ja: '「詳細度」を明記する。同じ範囲でも詳細度で工数が 5 倍変わる。', en: 'State the level of detail. For the same scope, detail can swing effort by five times.' },
      { ja: '受け入れ基準を成果物ごとに書く。「レビューを通ること」では基準にならない。', en: 'Write acceptance criteria per deliverable. "Passes review" is not a criterion.' },
      { ja: '変更が生じた場合の再承認プロセスを本文に入れておく。', en: 'Include the re-approval process for when scope changes.' },
    ],
    keywords: ['statement of architecture work', 'sow', '作業範囲', '記述書', 'スコープ', '承認', 'phase a'],
    template: [
      { heading: { ja: '1. 目的と背景', en: '1. Purpose and Background' }, guidance: { ja: '作業依頼書の内容を要約し、アーキテクトの理解として書き直す。', en: 'Summarize the request and restate it as the architect\'s understanding.' } },
      { heading: { ja: '2. 作業範囲', en: '2. Scope of Work' }, guidance: { ja: '組織範囲・ドメイン(B/C/D のどこまで)・時間軸・詳細度の 4 軸で書く。', en: 'Four axes: organizational coverage, domains (how far into B/C/D), time horizon, level of detail.' } },
      { heading: { ja: '3. 成果物と受け入れ基準', en: '3. Deliverables and Acceptance Criteria' }, guidance: { ja: '成果物ごとに 1 行の受け入れ基準を書く。', en: 'One line of acceptance criteria per deliverable.' } },
      { heading: { ja: '4. 体制とスケジュール', en: '4. Team and Schedule' }, guidance: { ja: '役割・氏名・稼働率・マイルストーン。', en: 'Role, name, allocation, milestones.' } },
      { heading: { ja: '5. 前提・制約・依存関係', en: '5. Assumptions, Constraints, Dependencies' }, guidance: { ja: '崩れたら計画を見直す前提を明示する。', en: 'Name the assumptions whose failure would force a re-plan.' } },
      { heading: { ja: '6. 変更管理', en: '6. Change Control' }, guidance: { ja: '範囲変更時の再承認の手順と承認者。', en: 'The re-approval procedure and approver for scope changes.' } },
      { heading: { ja: '7. 承認', en: '7. Approval' }, guidance: { ja: 'スポンサー名・役職・承認日。', en: 'Sponsor name, title, approval date.' } },
    ],
  },
  {
    id: 'stakeholder-map',
    name: { ja: 'ステークホルダーマップ', en: 'Stakeholder Map' },
    summary: {
      ja: '関係者・関心事・影響力・関与方針を一覧化した成果物。誰にどのビューを見せるかの設計図でもある。',
      en: 'A catalog of stakeholders, concerns, influence, and engagement approach. It doubles as the design for which view each audience is shown.',
    },
    createdInPhaseIds: ['a'],
    refinedInPhaseIds: ['b', 'c', 'd', 'g', 'h'],
    contents: [
      { ja: '氏名・役職・所属', en: 'Name, title, organization' },
      { ja: '関心事(具体的に。「品質」ではなく「月末処理が止まらないこと」)', en: 'Concerns, stated concretely — not "quality" but "month-end must not stall"' },
      { ja: '影響力と関心度の評価', en: 'Assessed power and interest' },
      { ja: '関与方針と担当アーキテクト', en: 'Engagement approach and the architect who owns the relationship' },
      { ja: '関心事に応えるビュー・成果物', en: 'The view or deliverable that answers each concern' },
    ],
    tips: [
      { ja: '反対者・懐疑派を必ず載せる。載っていないマップは使い物にならない。', en: 'Always include the sceptics and opponents. A map without them is useless.' },
      { ja: '関心事は本人の言葉で引用する。要約すると本質が抜ける。', en: 'Quote concerns in the person\'s own words. Summarizing loses the point.' },
    ],
    keywords: ['stakeholder', 'ステークホルダー', 'マップ', '関心事', 'concerns', '影響力'],
    template: [
      { heading: { ja: '1. 目的と使う場面', en: '1. Purpose and When It Is Used' }, guidance: { ja: '誰がいつこのマップを開くのかを先に決める。使う場面のないマップは、作った週から古くなる。', en: 'Decide who opens this map and when. A map with no moment of use starts going stale the week it is written.' } },
      { heading: { ja: '2. 一覧の列定義', en: '2. Column Definitions' }, guidance: { ja: '氏名 / 役職 / 所属 / 関心事 / 影響力 / 関心度 / 関与方針 / 担当アーキテクト の 8 列。関心事は本人の言葉のまま引用する。', en: 'Eight columns: name, title, organization, concern, influence, interest, engagement approach, owning architect. Quote the concern verbatim.' } },
      { heading: { ja: '3. 記入例', en: '3. Worked Example' }, guidance: { ja: '最初の 2 行を書いて粒度を示す。抽象的な関心事しか並ばない一覧は、埋める人が例を見ていない。', en: 'Write the first two rows to fix the granularity. A table of abstract concerns means nobody saw an example.' }, bullets: [
        { ja: '例: 経理部長 / 部長 / 経理部 / 「月次決算が 5 営業日を超えないこと」 / 高 / 高 / 重点管理・隔週で個別説明 / アーキテクト A', en: 'Example: Head of Finance / Director / Finance / "Month-end close must not exceed five working days" / High / High / Manage closely, fortnightly one-to-one / Architect A' },
        { ja: '例: 運用課長 / 課長 / IT 運用部 / 「夜間バッチの監視手順を変えたくない」 / 中 / 高 / 既存の運用定例で共有 / アーキテクト B', en: 'Example: Operations Manager / Manager / IT Operations / "Do not change how the nightly batch is monitored" / Medium / High / Share at the existing operations meeting / Architect B' },
      ] },
      { heading: { ja: '4. 影響力 × 関心度のマトリクス', en: '4. Influence / Interest Matrix' }, guidance: { ja: '4 象限(重点管理 / 満足を維持 / 情報提供 / 監視)に配置し、象限ごとの標準的な接し方を 1 行ずつ書く。', en: 'Place everyone in the four quadrants — manage closely, keep satisfied, keep informed, monitor — and give each quadrant a one-line standard approach.' } },
      { heading: { ja: '5. 関心事とビューの対応', en: '5. Concern-to-View Mapping' }, guidance: { ja: '関心事ごとに、それに答える成果物・ビューを 1 つ以上割り当てる。答えるものが無い関心事は、作業計画の抜けを指している。', en: 'Assign at least one deliverable or view to every concern. A concern with nothing answering it is a hole in the work plan.' } },
      { heading: { ja: '6. 反対者・懐疑派', en: '6. Sceptics and Opponents' }, guidance: { ja: '別節で明示的に扱う。懸念の内容・その理由・説得の担当者を書く。ここが空欄のマップは現実を写していない。', en: 'Handle them in their own section: the objection, why they hold it, and who owns the relationship. A map with this section empty is not describing reality.' } },
      { heading: { ja: '7. 更新ルール', en: '7. Maintenance Rules' }, guidance: { ja: '誰が、どの頻度で、何をきっかけに更新するか。組織改編とフェーズ切替は必ず見直しの契機にする。', en: 'Who updates it, how often, and on what trigger. Reorganizations and phase transitions must always force a review.' } },
    ],
  },
  {
    id: 'communications-plan',
    name: { ja: 'コミュニケーション計画', en: 'Communications Plan' },
    summary: {
      ja: '誰に、何を、いつ、どの形式で伝えるかを定義した計画。EA の成果物は「作ること」ではなく「伝わること」で価値が出るため、この計画の質が成否に直結する。',
      en: 'Defines who is told what, when, and in which format. EA deliverables create value by landing, not by existing, so the quality of this plan drives the outcome.',
    },
    createdInPhaseIds: ['a'],
    refinedInPhaseIds: ['b', 'c', 'd', 'e', 'f', 'g'],
    contents: [
      { ja: '対象者ごとの伝達内容と粒度', en: 'What each audience is told, and at what depth' },
      { ja: '頻度・タイミング(節目、定例)', en: 'Frequency and timing: milestones and regular cadence' },
      { ja: '形式(1 枚資料、ワークショップ、定義書、ダッシュボード)', en: 'Format: one-pager, workshop, definition document, dashboard' },
      { ja: '発信者と承認者', en: 'Who sends it and who approves it' },
      { ja: 'フィードバックの受け口', en: 'Where feedback comes back in' },
    ],
    tips: [
      { ja: '経営層向けは「1 枚 + 3 分」を基準に設計する。', en: 'Design executive communication around "one page, three minutes".' },
      { ja: '悪い知らせほど早く、定例を待たずに伝える経路を作っておく。', en: 'Build a route for bad news that does not wait for the next scheduled meeting.' },
    ],
    keywords: ['communication', 'コミュニケーション', '計画', '報告', '説明', 'レポート'],
    template: [
      { heading: { ja: '1. 対象者のグループ分け', en: '1. Audience Grouping' }, guidance: { ja: '対象者を 3〜5 グループに束ねる。個人ごとに資料を作り分ける計画は、2 週目で回らなくなる。', en: 'Collapse the audience into three to five groups. A plan with per-person materials collapses in its second week.' } },
      { heading: { ja: '2. 伝達計画表', en: '2. Communication Schedule' }, guidance: { ja: '対象 / 内容 / 粒度 / 形式 / 頻度 / 発信者 / 承認者 の 7 列の表で。', en: 'A seven-column table: audience, content, depth, format, frequency, sender, approver.' } },
      { heading: { ja: '3. 節目のコミュニケーション', en: '3. Milestone Communications' }, guidance: { ja: 'フェーズ完了・承認依頼・方針転換など、定例に乗らない山場を先に日付入りで置く。', en: 'Put the peaks that do not fit the regular cadence — phase completion, approval requests, changes of direction — on the calendar first.' } },
      { heading: { ja: '4. 定例への相乗り', en: '4. Riding Existing Meetings' }, guidance: { ja: '既存の会議体に枠をもらうことを優先する。新しい会議体を作るほど出席率は下がる。', en: 'Prefer a slot in a meeting that already exists. Every new meeting you create lowers attendance.' } },
      { heading: { ja: '5. 悪い知らせの経路', en: '5. The Bad-News Route' }, guidance: { ja: '定例を待たずに上げる条件・宛先・手段を決める。ここを設計していない案件では、問題は必ず手遅れになってから表に出る。', en: 'Define the trigger, the recipient, and the channel for news that cannot wait. Without this, problems surface only after they are unfixable.' } },
      { heading: { ja: '6. フィードバックの受け口', en: '6. Feedback Channel' }, guidance: { ja: '意見・反論をどこで受け、どう成果物に反映し、いつ返すか。反映されないと分かった時点で誰も答えなくなる。', en: 'Where comments arrive, how they reach the deliverable, and when the reply goes back. Once people see nothing changes, the comments stop.' } },
      { heading: { ja: '7. 用語と表現の方針', en: '7. Language and Terminology' }, guidance: { ja: '経営層向けに避ける専門用語と、その言い換えを列挙する。経営層向けは「1 枚 + 3 分」を基準に設計する。', en: 'List the jargon to avoid with executives and its replacement. Design executive material around "one page, three minutes".' } },
    ],
  },
  {
    id: 'architecture-definition-document',
    name: { ja: 'アーキテクチャ定義書', en: 'Architecture Definition Document' },
    summary: {
      ja: 'B〜D で作られる中核文書。ビジネス・データ・アプリケーション・テクノロジーの各ドメインについて、現行と目標のアーキテクチャ、およびその差分を記述する。ADD と略される。',
      en: 'The core document produced across Phases B–D. It describes baseline and target architectures — and the delta — for the business, data, application, and technology domains. Commonly abbreviated ADD.',
    },
    createdInPhaseIds: ['b', 'c', 'd'],
    refinedInPhaseIds: ['e', 'f', 'g', 'h'],
    contents: [
      { ja: 'スコープ・前提・制約(作業範囲記述書との整合)', en: 'Scope, assumptions, constraints, consistent with the Statement of Architecture Work' },
      { ja: 'ビジネスアーキテクチャ(現行/目標): 能力、バリューストリーム、プロセス、組織', en: 'Business architecture, baseline and target: capabilities, value streams, processes, organization' },
      { ja: 'データアーキテクチャ(現行/目標): 主要エンティティ、正本、ライフサイクル', en: 'Data architecture, baseline and target: key entities, systems of record, lifecycle' },
      { ja: 'アプリケーションアーキテクチャ(現行/目標): 論理構成要素、機能配置、連携', en: 'Application architecture, baseline and target: logical components, function placement, interfaces' },
      { ja: 'テクノロジーアーキテクチャ(現行/目標): プラットフォーム、配置、運用、セキュリティ', en: 'Technology architecture, baseline and target: platform, placement, operations, security' },
      { ja: 'ドメイン横断のギャップ一覧', en: 'The consolidated cross-domain gap list' },
      { ja: 'ステークホルダー別ビュー', en: 'Views organized by stakeholder' },
    ],
    tips: [
      { ja: '全ドメインを同じ深さで書かない。案件の争点があるドメインを厚く書く。', en: 'Do not write every domain to the same depth. Go deep where the engagement\'s real argument is.' },
      { ja: '図とテキストの重複を避ける。図で伝わることを文章で繰り返すと保守されなくなる。', en: 'Avoid duplicating diagrams in prose. Repeated content stops being maintained.' },
      { ja: '各記述に「誰の関心事に答えているか」を注記すると、不要な章が可視化される。', en: 'Annotate each section with the concern it answers; the unnecessary chapters reveal themselves.' },
    ],
    keywords: ['add', 'architecture definition', 'アーキテクチャ定義書', '定義書', 'baseline', 'target', '現行', '目標'],
    template: [
      { heading: { ja: '1. スコープと前提', en: '1. Scope and Assumptions' }, guidance: { ja: '作業範囲記述書からの引き写しではなく、実作業で確定した範囲を書く。', en: 'Not a copy of the Statement of Architecture Work — the scope as actually settled during the work.' } },
      { heading: { ja: '2. ビジネスアーキテクチャ', en: '2. Business Architecture' }, guidance: { ja: '現行 / 目標 / ギャップ。能力とバリューストリームを軸に。', en: 'Baseline, target, gaps — organized around capabilities and value streams.' } },
      { heading: { ja: '3. データアーキテクチャ', en: '3. Data Architecture' }, guidance: { ja: '主要エンティティと正本システム。CRUD マトリクスを添付。', en: 'Key entities and their system of record. Attach the CRUD matrix.' } },
      { heading: { ja: '4. アプリケーションアーキテクチャ', en: '4. Application Architecture' }, guidance: { ja: '論理構成要素と連携。製品名は物理の節に分ける。', en: 'Logical components and interfaces. Keep product names in the physical section.' } },
      { heading: { ja: '5. テクノロジーアーキテクチャ', en: '5. Technology Architecture' }, guidance: { ja: '非機能要件との対応を明示する。', en: 'Show explicitly how each non-functional requirement is met.' } },
      { heading: { ja: '6. ギャップ一覧', en: '6. Consolidated Gaps' }, guidance: { ja: 'ドメイン横断で統合し、重複を排除した一覧。', en: 'Merged across domains with duplicates removed.' } },
      { heading: { ja: '7. ステークホルダー別ビュー', en: '7. Stakeholder Views' }, guidance: { ja: '関心事 → ビューの対応表を先頭に置く。', en: 'Lead with the concern-to-view mapping table.' } },
    ],
  },
  {
    id: 'architecture-requirements-spec',
    name: { ja: 'アーキテクチャ要件仕様', en: 'Architecture Requirements Specification' },
    summary: {
      ja: 'アーキテクチャが満たすべき要件を、測定可能な形で列挙した文書。要件管理を通じて全フェーズで更新され続ける。実装チームへの受け渡しの中核でもある。',
      en: 'A list of the requirements the architecture must satisfy, stated measurably. It is maintained across every phase through Requirements Management and is the core of the handover to delivery teams.',
    },
    createdInPhaseIds: ['b', 'c', 'd', 'requirements-management'],
    refinedInPhaseIds: ['e', 'f', 'g', 'h'],
    contents: [
      { ja: '要件 ID・出所・提起者', en: 'Requirement ID, source, and who raised it' },
      { ja: '要件記述(検証可能な形で)', en: 'The requirement, stated so it can be verified' },
      { ja: '種別(機能/非機能/制約/規制)と優先度', en: 'Type — functional, non-functional, constraint, regulatory — and priority' },
      { ja: '受け入れ基準・測定方法', en: 'Acceptance criteria and how it will be measured' },
      { ja: '関連する成果物・アーキテクチャ構成要素へのトレース', en: 'Traceability to deliverables and architecture components' },
      { ja: '状態(提案/承認/実装済/却下)', en: 'State: proposed, approved, implemented, rejected' },
    ],
    tips: [
      { ja: '非機能要件には必ず数値と測定条件を書く。「高速に」は要件ではない。', en: 'Non-functional requirements need a number and the conditions of measurement. "Fast" is not a requirement.' },
      { ja: '却下要件も残す。同じ要求が形を変えて再提出されたときに議論を短縮できる。', en: 'Keep rejected requirements. When the same ask returns in new clothes, the debate is much shorter.' },
    ],
    keywords: ['requirements', '要件', '要件仕様', 'specification', '非機能', 'traceability', 'トレーサビリティ'],
    template: [
      { heading: { ja: '1. スコープと出典', en: '1. Scope and Sources' }, guidance: { ja: 'この仕様が扱う範囲と、要件をどこから集めたか(ワークショップ、規制文書、既存仕様)を書く。出典不明の要件は後で誰も守らせられない。', en: 'The scope covered and where the requirements came from: workshops, regulations, existing specifications. A requirement with no source cannot later be enforced.' } },
      { heading: { ja: '2. 要件一覧の列定義', en: '2. Requirement Table Columns' }, guidance: { ja: 'ID / 記述 / 種別 / 出所 / 優先度 / 受け入れ基準 / 状態 / トレース先 の 8 列。ID は一度振ったら再利用しない。', en: 'Eight columns: ID, statement, type, source, priority, acceptance criteria, state, traceability. Never reuse an ID once issued.' } },
      { heading: { ja: '3. 機能要件', en: '3. Functional Requirements' }, guidance: { ja: '「誰が何をできる」の形で書く。実装手段を書き込むと、設計の選択肢を要件の顔をして先に潰すことになる。', en: 'Write them as "who can do what". Naming an implementation here kills design options while disguised as a requirement.' } },
      { heading: { ja: '4. 非機能要件', en: '4. Non-Functional Requirements' }, guidance: { ja: '数値と測定条件をセットで書く。「高速に」「安定して」は要件ではなく願望。', en: 'Every entry needs a number and the measurement conditions. "Fast" and "stable" are wishes, not requirements.' }, bullets: [
        { ja: '性能: 対象処理 / 目標値 / 測定条件(同時実行数、データ量)', en: 'Performance: which operation, target value, measurement conditions (concurrency, data volume)' },
        { ja: '可用性: 稼働率 / 計画停止の扱い / 復旧目標(RTO・RPO)', en: 'Availability: uptime, treatment of planned outages, recovery targets (RTO, RPO)' },
        { ja: 'セキュリティ: 認証・認可の要求 / 監査ログの保持 / データ機密区分', en: 'Security: authentication and authorization requirements, audit-log retention, data classification' },
        { ja: '運用性: 監視項目 / 障害時の一次対応の担い手 / 保守作業の時間帯', en: 'Operability: what is monitored, who takes first response, permitted maintenance windows' },
      ] },
      { heading: { ja: '5. 制約と規制要件', en: '5. Constraints and Regulatory Requirements' }, guidance: { ja: '交渉の余地がないものだけを置く。「できれば」をここに混ぜると、本物の制約まで交渉可能に見える。', en: 'Only the non-negotiable belongs here. Mixing in "preferably" makes the genuine constraints look negotiable too.' } },
      { heading: { ja: '6. 優先度づけ', en: '6. Prioritization' }, guidance: { ja: '基準を 1 つに決め(MoSCoW など)、最高優先度の件数を全体の半分未満に抑える。全部が必須なら優先度は存在しない。', en: 'Pick one scheme (MoSCoW or similar) and keep the top tier under half the total. If everything is mandatory, there is no priority.' } },
      { heading: { ja: '7. トレーサビリティ', en: '7. Traceability' }, guidance: { ja: '要件 → 成果物 → 構成要素 → 検証方法 の連鎖を表にする。鎖の切れている箇所が、そのまま実装で落ちる箇所になる。', en: 'Tabulate the chain requirement to deliverable to component to verification. Wherever the chain breaks is where delivery will drop it.' } },
      { heading: { ja: '8. 却下要件の記録', en: '8. Rejected Requirements' }, guidance: { ja: '却下した要件と理由を残す。同じ要求が形を変えて再提出されたとき、議論を最初からやり直さずに済む。', en: 'Keep what you rejected and why. When the same ask returns in new clothes, you do not restart the argument from zero.' } },
    ],
  },
  {
    id: 'business-capability-map',
    name: { ja: 'ビジネス能力マップ', en: 'Business Capability Map' },
    summary: {
      ja: '事業が「何をできるか」を階層構造で表した図・一覧。組織やプロセスの変更に影響されにくく、投資の議論の共通言語になる。',
      en: 'A hierarchical view of what the business is able to do. It is stable across reorgs and process change, which makes it a shared language for investment discussions.',
    },
    createdInPhaseIds: ['b'],
    refinedInPhaseIds: ['c', 'e', 'h'],
    contents: [
      { ja: '能力の階層(通常 2〜3 階層)', en: 'The capability hierarchy, usually two or three levels' },
      { ja: '能力ごとの定義(何ができることを指すのか)', en: 'A definition per capability: what being able to do it means' },
      { ja: '能力の責任者', en: 'The owner of each capability' },
      { ja: '現在水準・目標水準の評価', en: 'Current and target maturity ratings' },
      { ja: '能力を支える組織・プロセス・システム・情報の対応', en: 'The organizations, processes, systems, and information that support it' },
    ],
    tips: [
      { ja: '動詞ではなく名詞で書く(「受注する」ではなく「受注管理」)。プロセスとの混同を防げる。', en: 'Name capabilities as nouns, not verbs ("order management", not "take orders"). It prevents confusion with process.' },
      { ja: '色分け(ヒートマップ)は 1 つの軸だけにする。複数軸を同時に塗ると読めない。', en: 'Heat-map on one dimension only. Colouring several at once makes it unreadable.' },
    ],
    keywords: ['capability', '能力', 'ケイパビリティ', 'マップ', 'heatmap', 'ヒートマップ', 'ビジネス'],
    template: [
      { heading: { ja: '1. 目的と使い道', en: '1. Purpose and Intended Use' }, guidance: { ja: '投資判断 / 重複排除 / 責任の明確化 のどれに使うのかを 1 つに決める。用途によって必要な階層の深さが変わる。', en: 'Choose one use — investment decisions, duplication removal, or clarifying ownership. The use determines how deep the hierarchy needs to go.' } },
      { heading: { ja: '2. 能力の階層', en: '2. Capability Hierarchy' }, guidance: { ja: 'L1 は 10〜20 個、L2 までを目安に。名詞で書き、プロセス名や組織名を混ぜない(「受注する」ではなく「受注管理」)。', en: 'Aim for 10 to 20 at level 1 and stop at level 2. Use nouns, and keep process and org names out ("order management", not "take orders").' } },
      { heading: { ja: '3. 能力の定義一覧', en: '3. Capability Definitions' }, guidance: { ja: '能力 ID / 名称 / 定義 / 責任者 の 4 列。定義は「何ができる状態か」を一文で書く。', en: 'Four columns: ID, name, definition, owner. Define each as one sentence describing what being able to do it looks like.' } },
      { heading: { ja: '4. 評価軸と現状 / 目標水準', en: '4. Rating Scale, Current and Target' }, guidance: { ja: '評価軸を 1 つに絞り(例: 成熟度 1〜5)、現状・目標・差を記録する。採点基準を文章で先に決めないと部門ごとに甘辛が出る。', en: 'Pick a single scale (maturity 1 to 5, say) and record current, target, and gap. Without a written rating rubric each unit scores differently.' } },
      { heading: { ja: '5. ヒートマップ', en: '5. Heat Map' }, guidance: { ja: '1 つの軸だけで色を塗る。複数軸を同時に塗った図は、作った本人以外には読めない。', en: 'Colour on one dimension only. Overlay several and only the author can read the picture.' } },
      { heading: { ja: '6. 支援資産の対応', en: '6. Supporting Assets' }, guidance: { ja: '能力ごとに、それを支えるプロセス・システム・情報・組織を紐づける。重複投資と空白がここで初めて見える。', en: 'Link each capability to the processes, systems, information, and organizations behind it. Duplicated investment and blank spots only appear here.' } },
      { heading: { ja: '7. 更新のきっかけ', en: '7. Update Triggers' }, guidance: { ja: '能力の構造は事業戦略の改訂時に見直し、組織改編では変えない — 組織に依存しないことが共通言語としての価値だから。ただし責任者の欄だけは組織改編のたびに更新する。', en: 'Revisit the structure when business strategy changes, not when the org chart does — independence from the org chart is what makes it a common language. The owner column is the one exception: refresh it at every reorganization.' } },
    ],
  },
  {
    id: 'application-portfolio-catalog',
    name: { ja: 'アプリケーションポートフォリオカタログ', en: 'Application Portfolio Catalog' },
    summary: {
      ja: '組織が保有するアプリケーションの一覧と属性。刷新・統廃合の判断材料であり、フェーズ C の現行分析の土台になる。',
      en: 'The inventory of applications the organization owns, with attributes. It is the evidence base for rationalization decisions and the foundation of baseline analysis in Phase C.',
    },
    createdInPhaseIds: ['c'],
    refinedInPhaseIds: ['d', 'e', 'h'],
    contents: [
      { ja: 'アプリケーション名・業務所管・IT 所管', en: 'Application name, business owner, IT owner' },
      { ja: '支援する業務機能・能力', en: 'The business functions and capabilities it supports' },
      { ja: '利用者数・重要度・稼働環境', en: 'User count, criticality, hosting environment' },
      { ja: '技術構成・サポート期限・保守費用', en: 'Technology stack, support end-of-life, maintenance cost' },
      { ja: '事業価値と技術的健全性の評価(廃止/維持/更改/置換の判定)', en: 'Business value and technical health ratings, leading to a retire / maintain / upgrade / replace verdict' },
    ],
    tips: [
      { ja: '「事業価値 × 技術的健全性」の 2 軸評価まで入れて初めて意思決定に使える。一覧だけでは動かない。', en: 'Only with the two-axis rating — business value against technical health — does the catalog drive decisions. A bare list changes nothing.' },
      { ja: 'シャドー IT を拾うため、部門の経費申請から逆引きすると精度が上がる。', en: 'Cross-check against departmental expense claims to surface shadow IT; accuracy improves markedly.' },
    ],
    keywords: ['application', 'アプリケーション', 'portfolio', 'ポートフォリオ', 'カタログ', 'システム一覧', '棚卸し', '刷新'],
    template: [
      { heading: { ja: '1. 対象範囲と収集方法', en: '1. Scope and Collection Method' }, guidance: { ja: 'どこまでを 1 アプリケーションと数えるか(業務マクロ、SaaS、内製ツール)を先に定義する。定義が曖昧だと、集計した人によって件数が倍違う。', en: 'Define what counts as one application — spreadsheet macros, SaaS, in-house tools — before collecting. Left vague, two people counting the same estate will differ by a factor of two.' } },
      { heading: { ja: '2. 列定義', en: '2. Column Definitions' }, guidance: { ja: 'アプリ ID / 名称 / 業務所管 / IT 所管 / 支援する能力 / 利用者数 / 重要度 / 稼働環境 / 技術構成 / サポート期限 / 年間費用 / 判定 の 12 列。', en: 'Twelve columns: ID, name, business owner, IT owner, capabilities supported, users, criticality, hosting, technology stack, support end date, annual cost, verdict.' } },
      { heading: { ja: '3. 記入例', en: '3. Worked Example' }, guidance: { ja: '2 行書いて粒度と表記を固定する。特に「支援する能力」は能力マップの ID を引く。', en: 'Two rows fix the granularity and notation. In particular, cite capability IDs from the capability map rather than free text.' }, bullets: [
        { ja: '例: APP-014 / 受注管理システム / 営業企画部 / 基幹システム課 / 受注管理・与信 / 320 名 / 高 / オンプレミス / 旧世代 Java・商用 RDB / 2027-03 / 4,200 万円 / 置換', en: 'Example: APP-014 / Order Management / Sales Planning / Core Systems team / Order management, credit check / 320 users / High / On-premises / Legacy Java, commercial RDB / 2027-03 / JPY 42M / Replace' },
        { ja: '例: APP-052 / 経費精算 SaaS / 経理部 / 情報システム部 / 経費管理 / 2,100 名 / 中 / SaaS / ベンダー提供 / 契約継続中 / 900 万円 / 維持', en: 'Example: APP-052 / Expense SaaS / Finance / IT department / Expense management / 2,100 users / Medium / SaaS / Vendor-managed / Contract ongoing / JPY 9M / Maintain' },
      ] },
      { heading: { ja: '4. 事業価値 × 技術的健全性の評価', en: '4. Business Value / Technical Health Rating' }, guidance: { ja: '各軸を 1〜5 で採点し 4 象限に配置する。採点基準を文章で先に決めなければ、部門ごとの甘辛で象限が意味を失う。', en: 'Score each axis 1 to 5 and plot the four quadrants. Without a written rubric, differing generosity between units empties the quadrants of meaning.' } },
      { heading: { ja: '5. 判定(廃止 / 維持 / 更改 / 置換)', en: '5. Verdict: Retire / Maintain / Upgrade / Replace' }, guidance: { ja: '象限からの機械的な導出を書き、覆す場合は理由を併記する。理由なき例外を許すと台帳全体が信用されなくなる。', en: 'State the mechanical derivation from the quadrant, and record the reason whenever it is overridden. Unexplained exceptions discredit the whole catalog.' } },
      { heading: { ja: '6. シャドー IT の扱い', en: '6. Handling Shadow IT' }, guidance: { ja: '経費申請・SaaS 課金・SSO ログから逆引きして拾う。拾ったものを罰しない運用にしないと、次からは二度と出てこない。', en: 'Surface it from expense claims, SaaS billing, and SSO logs. If what you find gets punished, nothing will ever surface again.' } },
      { heading: { ja: '7. 更新ルール', en: '7. Maintenance Rules' }, guidance: { ja: '調達・廃止のワークフローに登録と更新を組み込む。年 1 回の棚卸しだけに頼るカタログは、常に半年古い。', en: 'Wire registration and update into the procurement and decommissioning workflows. A catalog refreshed once a year is permanently six months out of date.' } },
    ],
  },
  {
    id: 'data-entity-catalog',
    name: { ja: 'データエンティティカタログ', en: 'Data Entity Catalog' },
    summary: {
      ja: '主要な業務データの一覧と、その正本・利用範囲・管理責任を整理した成果物。マスタデータ統合やデータガバナンスの出発点になる。',
      en: 'A catalog of the key business data entities with their system of record, usage, and stewardship. It is the starting point for master data consolidation and data governance.',
    },
    createdInPhaseIds: ['c'],
    refinedInPhaseIds: ['d', 'e', 'h'],
    contents: [
      { ja: 'エンティティ名と業務上の定義', en: 'Entity name and business definition' },
      { ja: '正本システム(system of record)', en: 'System of record' },
      { ja: 'データ管理責任者(データスチュワード)', en: 'Data steward' },
      { ja: '作成・参照・更新・削除するシステム(CRUD)', en: 'Systems that create, read, update, delete it' },
      { ja: '機密区分・保持期間・規制要件', en: 'Sensitivity classification, retention period, regulatory requirements' },
    ],
    tips: [
      { ja: '定義の食い違いこそが本題。「顧客」の定義が部門ごとに違うことを可視化するだけで価値がある。', en: 'The definitional disagreements are the point. Simply exposing that each unit defines "customer" differently already delivers value.' },
      { ja: '全データを網羅しようとしない。争点になる 20〜30 エンティティで十分。', en: 'Do not aim for completeness. The twenty or thirty contested entities are enough.' },
    ],
    keywords: ['data', 'データ', 'エンティティ', 'entity', 'master data', 'マスタ', 'crud', 'system of record', '正本'],
    template: [
      { heading: { ja: '1. 対象範囲の絞り込み', en: '1. Narrowing the Scope' }, guidance: { ja: '全データを網羅しない。部門間で定義が食い違うもの、複数システムに散在するものを 20〜30 件選ぶ。網羅を狙った瞬間に完成しなくなる。', en: 'Do not aim for completeness. Pick the 20 to 30 entities that are defined differently across units or scattered across systems. Aiming for everything guarantees it never finishes.' } },
      { heading: { ja: '2. 列定義', en: '2. Column Definitions' }, guidance: { ja: 'エンティティ ID / 名称 / 業務定義 / 正本システム / データスチュワード / 機密区分 / 保持期間 / 関連規制 の 8 列。', en: 'Eight columns: ID, name, business definition, system of record, data steward, sensitivity, retention period, applicable regulation.' } },
      { heading: { ja: '3. 記入例', en: '3. Worked Example' }, guidance: { ja: '2 行書いて定義の粒度を示す。スチュワードは部署名ではなく個人で書く。', en: 'Two rows show the expected granularity of the definition. Name a person as steward, never a department.' }, bullets: [
        { ja: '例: ENT-003 / 顧客 / 契約中または見込みのある法人・個人 / 顧客マスタ(CRM) / 営業企画部 担当者名 / 機密 / 契約終了後 7 年 / 個人情報関連法令', en: 'Example: ENT-003 / Customer / A company or individual under contract or in the pipeline / Customer master (CRM) / named person, Sales Planning / Confidential / 7 years after contract end / Personal data legislation' },
        { ja: '例: ENT-011 / 商品 / 販売可能な単位で管理する品目 / 商品マスタ(基幹) / 商品部 担当者名 / 社内限 / 廃番後 5 年 / なし', en: 'Example: ENT-011 / Product / An item managed as a sellable unit / Product master (core system) / named person, Product division / Internal / 5 years after discontinuation / None' },
      ] },
      { heading: { ja: '4. 定義の食い違いの記録', en: '4. Recording Definitional Conflicts' }, guidance: { ja: '同じ名前で違う意味に使われている語を、部門ごとの定義を並べて可視化する。ここが本題であり、統一案を急いで出す節ではない。', en: 'For each contested term, list the definitions side by side per unit. Exposing the conflict is the point; this is not the section where you rush a unified definition.' } },
      { heading: { ja: '5. CRUD マトリクス', en: '5. CRUD Matrix' }, guidance: { ja: '行にエンティティ、列にシステムを取り C/R/U/D を入れる。C が複数あるエンティティが、統合の最優先候補になる。', en: 'Entities down, systems across, C/R/U/D in the cells. Entities with more than one C are the top consolidation candidates.' } },
      { heading: { ja: '6. 正本の決定', en: '6. Deciding the System of Record' }, guidance: { ja: 'エンティティごとに正本を 1 つに決め、決めた理由と決定日を残す。「暫定」と書かれたまま数年放置された正本は正本ではない。', en: 'Settle on exactly one per entity and record the reason and the date. A system of record still labelled "provisional" after two years is not one.' } },
      { heading: { ja: '7. 機密区分と規制', en: '7. Classification and Regulation' }, guidance: { ja: '区分ごとの取り扱い規則(保管場所、暗号化、越境移転の可否)への参照を張る。区分だけ付けて規則を書かないと運用に落ちない。', en: 'Link each class to its handling rules: storage location, encryption, cross-border transfer. A class with no rules behind it never reaches operations.' } },
      { heading: { ja: '8. 更新ルール', en: '8. Maintenance Rules' }, guidance: { ja: '新規システム導入時と規制改正時に見直す。スチュワードが異動で不在になったエンティティは、その場で後任を立てる。', en: 'Review on new system introductions and regulatory change. When a steward moves on, name the successor immediately rather than later.' } },
    ],
  },
  {
    id: 'technology-standards-catalog',
    name: { ja: '技術標準カタログ', en: 'Technology Standards Catalog' },
    summary: {
      ja: '組織として認めた技術・製品・バージョンの一覧と、その位置づけ(推奨/許容/非推奨/廃止予定)。技術選定の判断を高速化し、乱立を防ぐ。',
      en: 'The list of technologies, products, and versions the organization sanctions, each with a status: preferred, acceptable, discouraged, or retiring. It speeds technology selection and curbs sprawl.',
    },
    createdInPhaseIds: ['d'],
    refinedInPhaseIds: ['g', 'h'],
    contents: [
      { ja: '技術分類(実行基盤、DB、連携、監視、認証 など)', en: 'Technology category: runtime, database, integration, monitoring, identity, and so on' },
      { ja: '製品・バージョンと位置づけ(推奨/許容/非推奨/廃止予定)', en: 'Product and version with status: preferred, acceptable, discouraged, retiring' },
      { ja: '適用条件と例外の扱い', en: 'Conditions of use and how exceptions are handled' },
      { ja: 'サポート期限と移行先', en: 'Support end date and the migration destination' },
      { ja: '所管部門・問い合わせ先', en: 'Owning team and where to ask' },
    ],
    tips: [
      { ja: '「廃止予定」に必ず移行先を書く。移行先のない廃止予定は無視される。', en: 'Every "retiring" entry needs a destination. Without one it is simply ignored.' },
      { ja: '更新の頻度と責任者を決める。放置された標準カタログは有害。', en: 'Fix the update cadence and owner. A stale standards catalog does active harm.' },
    ],
    keywords: ['technology', '技術標準', 'standards', 'カタログ', '製品', 'version', 'eol', 'サポート期限'],
    template: [
      { heading: { ja: '1. 分類体系', en: '1. Category Scheme' }, guidance: { ja: '技術分類を先に決める(実行基盤 / データストア / 連携 / 監視 / 認証 / 開発ツール など)。分類が無いと、同じ用途の製品が別々の場所に登録されて乱立に気づけない。', en: 'Fix the categories first: runtime, data store, integration, monitoring, identity, developer tooling. Without them, products serving the same purpose land in different places and the sprawl goes unnoticed.' } },
      { heading: { ja: '2. 列定義', en: '2. Column Definitions' }, guidance: { ja: '分類 / 製品 / バージョン / 位置づけ / 適用条件 / サポート期限 / 移行先 / 所管 の 8 列。バージョンまで書かないと標準として機能しない。', en: 'Eight columns: category, product, version, status, conditions of use, support end date, migration target, owning team. Without the version it is not a standard.' } },
      { heading: { ja: '3. 記入例', en: '3. Worked Example' }, guidance: { ja: '推奨と廃止予定を 1 行ずつ書いて記法を固定する。', en: 'One preferred row and one retiring row fix the notation.' }, bullets: [
        { ja: '例: 実行基盤 / コンテナ基盤 A / 1.28 / 推奨 / 新規の内製アプリはこれを使う / 2027-06 / — / 基盤課', en: 'Example: Runtime / Container platform A / 1.28 / Preferred / Use for all new in-house applications / 2027-06 / — / Platform team' },
        { ja: '例: データストア / RDB 製品 B / 12 / 廃止予定 / 新規採用不可 / 2026-12 / RDB 製品 B 19 / DB 課', en: 'Example: Data store / RDB product B / 12 / Retiring / No new adoption / 2026-12 / RDB product B 19 / Database team' },
      ] },
      { heading: { ja: '4. 位置づけの定義', en: '4. Status Definitions' }, guidance: { ja: '推奨 / 許容 / 非推奨 / 廃止予定 が何を意味するかを文章で定義する。特に「許容」で新規採用してよいのかを一義的に書く。', en: 'Write out what preferred, acceptable, discouraged, and retiring each mean. Above all, state unambiguously whether "acceptable" permits new adoption.' } },
      { heading: { ja: '5. 廃止予定と移行先', en: '5. Retirement and Migration Targets' }, guidance: { ja: '廃止予定には必ず移行先と期限を書く。移行先の無い廃止予定は、全員に無視されて期限だけが過ぎる。', en: 'Every retiring entry needs a destination and a date. A retirement with nowhere to go is ignored by everyone until the date has passed.' } },
      { heading: { ja: '6. 例外の申請と承認', en: '6. Exceptions' }, guidance: { ja: '標準外を使う場合の申請先・判断基準・有効期限を書く。期限のない例外は、時間が経てば事実上の標準になる。', en: 'Where to apply, on what criteria, and for how long. An exception with no expiry quietly becomes the standard.' } },
      { heading: { ja: '7. 更新ルール', en: '7. Maintenance Rules' }, guidance: { ja: '四半期ごとの見直しと、サポート期限情報を更新する責任者を決める。放置された標準カタログは、無いより有害。', en: 'A quarterly review and a named owner for keeping support dates current. A stale standards catalog is worse than none.' } },
    ],
  },
  {
    id: 'architecture-roadmap',
    name: { ja: 'アーキテクチャロードマップ', en: 'Architecture Roadmap' },
    summary: {
      ja: '現行から目標へ至る道筋を、作業パッケージと中間状態(移行アーキテクチャ)の時系列として表した成果物。フェーズ E で作られ、F で予算と体制が付く。',
      en: 'The path from baseline to target expressed as a timeline of work packages and intermediate states. Produced in Phase E and given budget and staffing in Phase F.',
    },
    createdInPhaseIds: ['e'],
    refinedInPhaseIds: ['f', 'g', 'h'],
    contents: [
      { ja: '作業パッケージ一覧(範囲、成果、規模)', en: 'Work packages with scope, outcome, and size' },
      { ja: '依存関係と実施順序', en: 'Dependencies and sequence' },
      { ja: '移行アーキテクチャ(中間状態)とその到達時期', en: 'Transition architectures and when each is reached' },
      { ja: '各段階で実現される事業価値', en: 'The business value realized at each step' },
      { ja: '前提・制約(予算サイクル、規制期日、要員)', en: 'Assumptions and constraints: budget cycle, regulatory dates, staffing' },
    ],
    tips: [
      { ja: '横軸を「四半期」にする。月単位は精度を装った嘘になり、年単位は判断に使えない。', en: 'Use quarters on the horizontal axis. Months fake a precision you do not have; years are useless for deciding.' },
      { ja: '各中間状態に「ここで止めても事業は回るか」の欄を作る。', en: 'Give every intermediate state a column: "can we stop here and still operate?"' },
    ],
    keywords: ['roadmap', 'ロードマップ', '計画', 'work package', '作業パッケージ', 'transition', '移行', '順序'],
    template: [
      { heading: { ja: '1. 前提と制約', en: '1. Assumptions and Constraints' }, guidance: { ja: '予算サイクル・規制期日・要員の空きを先に書く。', en: 'Lead with budget cycle, regulatory dates, and staff availability.' } },
      { heading: { ja: '2. 作業パッケージ一覧', en: '2. Work Packages' }, guidance: { ja: 'ID・名称・範囲・成果・規模・担当を表で。1 パッケージ 3〜6 か月を目安に。', en: 'A table of ID, name, scope, outcome, size, owner. Target three to six months each.' } },
      { heading: { ja: '3. 依存関係', en: '3. Dependencies' }, guidance: { ja: '技術依存だけでなく、予算・要員・組織の依存も書く。', en: 'Not only technical dependencies — budget, staffing, and organizational ones too.' } },
      { heading: { ja: '4. 移行アーキテクチャ(中間状態)', en: '4. Transition Architectures' }, guidance: { ja: '各状態: 到達時期 / 実現する能力 / ここで止めた場合の評価。', en: 'Per state: date reached, capability delivered, and what happens if you stop there.' } },
      { heading: { ja: '5. タイムライン', en: '5. Timeline' }, guidance: { ja: '四半期を横軸に。パッケージと中間状態を重ねて表示。', en: 'Quarters across the top, with packages and transition states overlaid.' } },
      { heading: { ja: '6. 各段階の事業価値', en: '6. Value at Each Step' }, guidance: { ja: '便益・測定指標・便益責任者。', en: 'Benefit, measure, and the person accountable for harvesting it.' } },
    ],
  },
  {
    id: 'transition-architecture',
    name: { ja: '移行アーキテクチャ', en: 'Transition Architecture' },
    summary: {
      ja: '現行と目標の間に置く、実際に到達・運用される中間状態のアーキテクチャ。各中間状態は単独で事業価値を出し、そこで止まっても運用できる必要がある。',
      en: 'An intermediate architecture that is actually reached and operated between baseline and target. Each one must deliver business value on its own and remain operable if the programme stops there.',
    },
    createdInPhaseIds: ['e'],
    refinedInPhaseIds: ['f', 'g'],
    contents: [
      { ja: 'その状態で実現している能力・機能', en: 'The capabilities and functions in place at that state' },
      { ja: '残っている現行構成要素と、共存のための仕組み', en: 'Which baseline components remain and how coexistence is handled' },
      { ja: 'その状態で発生する一時的な仕組み(暫定連携、二重運用)', en: 'Temporary machinery at that state: interim interfaces, dual running' },
      { ja: '到達条件と次の状態への移行条件', en: 'Entry criteria and the criteria for moving to the next state' },
      { ja: '一時的な仕組みの廃棄計画', en: 'The disposal plan for the temporary machinery' },
    ],
    tips: [
      { ja: '暫定の仕組みには必ず廃棄計画と期限を付ける。暫定が恒久化するのは、期限を書かなかったから。', en: 'Every interim mechanism needs a disposal plan and a date. Interim things become permanent precisely because no date was written.' },
      { ja: '二重運用の期間中のコストを見積もる。ここを過小評価した移行計画は必ず遅れる。', en: 'Estimate the cost of the dual-running period. Migration plans that understate it always slip.' },
    ],
    keywords: ['transition', '移行アーキテクチャ', '中間状態', 'interim', '暫定', '共存', '二重運用'],
    template: [
      { heading: { ja: '1. この中間状態の位置づけ', en: '1. Position in the Roadmap' }, guidance: { ja: 'ロードマップ上のどこに位置するか、到達予定の四半期、直前と直後の状態を書く。', en: 'Where it sits on the roadmap, the quarter it is reached, and the states immediately before and after.' } },
      { heading: { ja: '2. 到達条件', en: '2. Entry Criteria' }, guidance: { ja: '「この状態に到達した」と判定する条件を検証可能な形で書く。曖昧なままだと、移行が終わったかどうかを誰も宣言できない。', en: 'Write verifiable criteria for having arrived. Left vague, nobody can ever declare the migration step complete.' } },
      { heading: { ja: '3. 実現している能力', en: '3. Capabilities Delivered' }, guidance: { ja: 'この時点で使えるようになる能力と、まだ使えない能力を対で書く。期待値のずれはこの節で防ぐ。', en: 'List what becomes usable here alongside what still does not. This pairing is what prevents mismatched expectations.' } },
      { heading: { ja: '4. 残存する現行構成要素', en: '4. Remaining Baseline Components' }, guidance: { ja: '残る現行システムと、それぞれがいつまで残るか。「当面」と書かれた構成要素は永久に残る。', en: 'Which baseline systems remain and until when. Anything marked "for the time being" remains forever.' } },
      { heading: { ja: '5. 一時的な仕組み', en: '5. Interim Mechanisms' }, guidance: { ja: '暫定連携・データの二重持ち・並行運用を一覧にし、それぞれの目的と存在期間を書く。', en: 'List the interim interfaces, duplicated data, and parallel running, each with its purpose and lifespan.' } },
      { heading: { ja: '6. 廃棄計画', en: '6. Disposal Plan' }, guidance: { ja: '一時的な仕組みごとに廃棄の条件・期限・担当を書く。暫定が恒久化するのは、この節を書かなかった案件に限られる。', en: 'Per interim mechanism: the condition, the date, and the owner for removing it. Interim things become permanent only on engagements that skipped this section.' } },
      { heading: { ja: '7. ここで止めた場合の評価', en: '7. Assessment If You Stop Here' }, guidance: { ja: '事業として運用可能か、コストは許容できるかを書く。「止められる」ことを確認できて初めて中間状態として成立する。', en: 'Can the business run on it, and is the cost tolerable? A state only qualifies as a transition architecture once you have confirmed you could stop at it.' } },
      { heading: { ja: '8. 移行期のコストとリスク', en: '8. Cost and Risk During the Move' }, guidance: { ja: '二重運用の費用、切替時の停止時間、切り戻し手順。ここを過小評価した移行計画は必ず遅れる。', en: 'Dual-running cost, cutover downtime, and the rollback procedure. Migration plans that understate this always slip.' } },
    ],
  },
  {
    id: 'implementation-migration-plan',
    name: { ja: '実装移行計画', en: 'Implementation and Migration Plan' },
    summary: {
      ja: 'ロードマップに予算・体制・スケジュール・受け入れ基準を付けた実行計画。フェーズ F で完成し、既存のポートフォリオ/プロジェクト管理へ引き渡される。',
      en: 'The roadmap with budget, staffing, schedule, and acceptance criteria attached. Completed in Phase F and handed over to the existing portfolio and project management processes.',
    },
    createdInPhaseIds: ['f'],
    refinedInPhaseIds: ['g', 'h'],
    contents: [
      { ja: 'プロジェクト分割と実施順序', en: 'Breakdown into projects and their sequence' },
      { ja: 'コスト見積りと予算配分(年度別)', en: 'Cost estimates and budget allocation by fiscal year' },
      { ja: '便益と便益責任者、測定時期', en: 'Benefits, benefit owners, and when they are measured' },
      { ja: '体制・要員計画・必要スキル', en: 'Team structure, staffing plan, required skills' },
      { ja: 'マイルストーンと受け入れ基準', en: 'Milestones and acceptance criteria' },
      { ja: 'リスクと緩和策、残存リスクの受容者', en: 'Risks, mitigations, and who accepts the residual risk' },
      { ja: 'ガバナンス(レビュー時期、判断ポイント)', en: 'Governance: review points and decision gates' },
    ],
    tips: [
      { ja: '会計年度をまたぐ大きな塊は、年度内で完結する単位に割る。', en: 'Break anything that straddles fiscal years into units that complete within one.' },
      { ja: '中止判断のポイント(kill point)を計画に明記する。止められない計画は暴走する。', en: 'Write the kill points into the plan. A plan that cannot be stopped will run away.' },
    ],
    keywords: ['implementation', '実装', 'migration plan', '移行計画', '実行計画', '予算', 'budget', 'schedule', 'スケジュール'],
    template: [
      { heading: { ja: '1. 計画の前提', en: '1. Planning Assumptions' }, guidance: { ja: 'ロードマップからの変更点と、その理由。', en: 'What changed from the roadmap, and why.' } },
      { heading: { ja: '2. プロジェクト分割と順序', en: '2. Project Breakdown and Sequence' }, guidance: { ja: '年度内に完結する単位に割る。', en: 'Break into units that complete within a fiscal year.' } },
      { heading: { ja: '3. コストと予算配分', en: '3. Cost and Budget Allocation' }, guidance: { ja: '年度別・費目別。運用費の増分も忘れず入れる。', en: 'By year and category. Do not forget the increase in run cost.' } },
      { heading: { ja: '4. 便益と測定', en: '4. Benefits and Measurement' }, guidance: { ja: '便益 / 指標 / 便益責任者 / 測定時期 の 4 列。', en: 'Four columns: benefit, measure, benefit owner, measurement date.' } },
      { heading: { ja: '5. 体制と要員', en: '5. Team and Staffing' }, guidance: { ja: '必要スキルと、その充足手段(採用/育成/調達)。', en: 'Required skills and how they are met: hire, train, or contract.' } },
      { heading: { ja: '6. マイルストーンと受け入れ基準', en: '6. Milestones and Acceptance Criteria' }, guidance: { ja: '中止判断ポイント(kill point)を必ず入れる。', en: 'Include the kill points.' } },
      { heading: { ja: '7. リスクと残存リスク', en: '7. Risks and Residual Risk' }, guidance: { ja: '受容者は個人名で記載する。', en: 'Name a person as the acceptor.' } },
      { heading: { ja: '8. ガバナンスと引き渡し', en: '8. Governance and Handover' }, guidance: { ja: 'PMO との受け入れ基準の合意を含める。', en: 'Include the acceptance criteria agreed with the PMO.' } },
    ],
  },
  {
    id: 'architecture-contract',
    name: { ja: 'アーキテクチャ契約', en: 'Architecture Contract' },
    summary: {
      ja: 'アーキテクチャ機能と実装チーム(または供給者)の間で、守るべきアーキテクチャ上の取り決めを合意する文書。フェーズ G のガバナンスの実効性はこの契約の有無で決まる。',
      en: 'The agreement between the architecture function and the delivery team or supplier on the architectural commitments to be honoured. Whether Phase G governance has teeth depends on whether this exists.',
    },
    createdInPhaseIds: ['f', 'g'],
    refinedInPhaseIds: ['g', 'h'],
    contents: [
      { ja: '当事者と適用範囲', en: 'Parties and scope of application' },
      { ja: '遵守すべきアーキテクチャ要件・原則・標準', en: 'Architecture requirements, principles, and standards to be honoured' },
      { ja: 'レビューのタイミングと通過基準', en: 'Review points and pass criteria' },
      { ja: '適合性の測定方法と報告義務', en: 'How conformance is measured and the reporting obligations' },
      { ja: '例外申請の手順と承認者', en: 'The exception procedure and who approves' },
      { ja: '不適合時の扱い(是正、エスカレーション)', en: 'What happens on non-conformance: remediation and escalation' },
    ],
    tips: [
      { ja: '外部ベンダー案件では調達契約に組み込む。付属文書のままでは効力が薄い。', en: 'On vendor engagements, fold it into the procurement contract. Left as an annex it carries little weight.' },
      { ja: '守れない条項を入れない。1 つでも死文化すると契約全体が軽く扱われる。', en: 'Do not include clauses you will not enforce. One dead clause devalues the whole contract.' },
    ],
    keywords: ['contract', '契約', 'アーキテクチャ契約', 'ベンダー', 'vendor', '遵守', 'compliance', '調達'],
    template: [
      { heading: { ja: '1. 当事者と適用範囲', en: '1. Parties and Scope' }, guidance: { ja: '両当事者、対象プロジェクト・システム、有効期間を書く。外部ベンダー案件では調達契約への組み込み方も明記する。', en: 'Both parties, the projects and systems covered, and the term. On vendor engagements, state how it folds into the procurement contract.' } },
      { heading: { ja: '2. 遵守事項', en: '2. Commitments' }, guidance: { ja: '守るべき原則・標準・要件を ID で列挙する。本文を書き写すと、原本が改訂されたときに不整合が残る。', en: 'Cite the principles, standards, and requirements by ID. Copying the text in leaves you inconsistent the moment the source is revised.' } },
      { heading: { ja: '3. レビュー時期と通過基準', en: '3. Review Points and Pass Criteria' }, guidance: { ja: '設計・実装・受け入れの各段階で、何を見て通すかを書く。基準の無いレビューは押印だけの会議になる。', en: 'At design, build, and acceptance: what is examined and what passes. A review with no criteria is a rubber-stamp meeting.' } },
      { heading: { ja: '4. 適合性の測定と報告', en: '4. Conformance Measurement and Reporting' }, guidance: { ja: '何を、どの頻度で、どの形式で報告するか。自己申告のみとするなら、抜き取り確認の頻度も併せて決める。', en: 'What is reported, how often, in what form. If reporting is self-declared, fix the sampling frequency for spot checks too.' } },
      { heading: { ja: '5. 例外の申請と承認', en: '5. Exceptions' }, guidance: { ja: '申請先・判断基準・有効期限・再申請の可否。期限の無い例外を一度でも認めると、以降の申請はすべてそれを前例にする。', en: 'Where to apply, the criteria, the expiry, and whether renewal is allowed. Grant one exception without an expiry and every later application cites it as precedent.' } },
      { heading: { ja: '6. 不適合時の扱い', en: '6. Non-Conformance' }, guidance: { ja: '是正期限、エスカレーション先、それでも直らない場合の措置(支払保留、受け入れ拒否)。実行する気の無い措置は書かない。', en: 'Remediation deadline, escalation path, and the measure of last resort — payment hold, acceptance refusal. Do not write a measure you will not use.' } },
      { heading: { ja: '7. 変更管理', en: '7. Change Control' }, guidance: { ja: 'アーキテクチャ側が要件を変える場合の手順と、費用・期間の調整方法も書く。片務的な契約は必ず現場で無視される。', en: 'Include the procedure when the architecture side changes a requirement, and how cost and schedule are adjusted. A one-sided contract is ignored on the ground.' } },
      { heading: { ja: '8. 署名', en: '8. Signatures' }, guidance: { ja: '双方の責任者名・役職・日付。承認者が組織名のままの契約は、誰も守らない。', en: 'Name, title, and date for both sides. A contract signed by an organization rather than a person binds nobody.' } },
    ],
  },
  {
    id: 'compliance-assessment',
    name: { ja: 'アーキテクチャ適合性評価', en: 'Architecture Compliance Assessment' },
    summary: {
      ja: '実装がアーキテクチャに沿っているかを評価した記録。準拠の度合いを段階で判定し、逸脱については是正か例外承認かを決める。',
      en: 'The record of how far an implementation follows the architecture. Conformance is rated on a scale, and each deviation is resolved as either remediation or a granted exception.',
    },
    createdInPhaseIds: ['g'],
    refinedInPhaseIds: ['h'],
    contents: [
      { ja: '評価対象(プロジェクト、システム、時点)', en: 'What was assessed: project, system, point in time' },
      { ja: '評価項目と判定(準拠/一部準拠/非準拠/非適合)', en: 'Criteria and rating: conformant, partially conformant, non-conformant, irreconcilable' },
      { ja: '逸脱の内容と理由', en: 'The deviations and the reasons behind them' },
      { ja: '是正計画または例外承認(期限付き)', en: 'Remediation plan or granted exception, with an expiry date' },
      { ja: '次回評価の時期', en: 'The date of the next assessment' },
    ],
    tips: [
      { ja: '逸脱の「理由」を必ず記録する。理由の集計がアーキテクチャ改善の最良の材料になる。', en: 'Always record why a deviation happened. Aggregated reasons are the best input to improving the architecture itself.' },
      { ja: '評価は設計段階で行う。実装完了後の評価は、指摘しても直せない。', en: 'Assess at design time. Findings after implementation cannot be acted on.' },
    ],
    keywords: ['compliance', '適合性', '準拠', 'assessment', '評価', 'レビュー', '逸脱', 'deviation'],
    template: [
      { heading: { ja: '1. 評価の対象と時点', en: '1. Subject and Point in Time' }, guidance: { ja: '対象プロジェクト・システム、評価した設計書の版、評価日を書く。版を記録しないと「その後直した」と言われて決着しない。', en: 'The project or system, the version of the design reviewed, and the date. Without the version, "we fixed that afterwards" ends every discussion inconclusively.' } },
      { heading: { ja: '2. 評価者と参加者', en: '2. Assessors and Attendees' }, guidance: { ja: '評価者、被評価側の出席者、所要時間。設計者本人が出ていない評価は、指摘が伝わらない。', en: 'Who assessed, who attended from the delivery side, and how long it took. Findings from a session the designer did not attend rarely land.' } },
      { heading: { ja: '3. 評価項目と判定', en: '3. Criteria and Ratings' }, guidance: { ja: '項目 / 根拠(原則・標準 ID) / 判定 / 所見 の 4 列。判定は 準拠 / 一部準拠 / 非準拠 / 非適合 の 4 段階で(記載項目の用語に合わせる)。', en: 'Four columns: criterion, basis (principle or standard ID), rating, observation. Rate as conformant, partially conformant, non-conformant, or irreconcilable.' } },
      { heading: { ja: '4. 逸脱の内容と理由', en: '4. Deviations and Their Causes' }, guidance: { ja: '逸脱ごとに、なぜそうなったか(知らなかった / 標準が現実に合わない / 期限の都合)を分類して記録する。この理由の集計が、アーキテクチャ自体を直す最良の材料になる。', en: 'Classify each deviation by cause: unaware, standard does not fit reality, or schedule pressure. Aggregating these causes is the best input to fixing the architecture itself.' } },
      { heading: { ja: '5. 是正計画または例外承認', en: '5. Remediation or Granted Exception' }, guidance: { ja: '逸脱ごとに、是正するか例外を認めるかを決め、期限と担当を付ける。判断を保留した逸脱は、そのまま本番に出る。', en: 'Per deviation, decide remediation or exception, with a date and an owner. A deviation left undecided ships to production as it is.' } },
      { heading: { ja: '6. 総合判定と次回評価', en: '6. Overall Verdict and Next Review' }, guidance: { ja: '全体の判定と、次に見る時期・条件。次回が決まっていない評価は 1 回で終わる。', en: 'The overall rating and when or on what condition you look again. An assessment with no next date happens exactly once.' } },
      { heading: { ja: '7. 標準へのフィードバック', en: '7. Feedback to the Standards' }, guidance: { ja: '「標準が現実に合わない」に分類された逸脱を、標準改訂の提案として起票する。ここを閉じないと同じ逸脱が毎回出る。', en: 'Raise each "standard does not fit reality" deviation as a proposed revision. Leave the loop open and the same deviation returns every time.' } },
    ],
  },
  {
    id: 'requirements-impact-assessment',
    name: { ja: '要件影響評価', en: 'Requirements Impact Assessment' },
    summary: {
      ja: '要件の新規追加・変更が、どのフェーズ・成果物・実装に影響するかを評価した記録。要件管理の中核成果物であり、再作業の要否判断の根拠になる。',
      en: 'The record of which phases, deliverables, and implementations a new or changed requirement affects. It is the core artifact of Requirements Management and the basis for deciding whether rework is needed.',
    },
    createdInPhaseIds: ['requirements-management'],
    refinedInPhaseIds: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    contents: [
      { ja: '対象要件 ID と変更内容', en: 'The requirement ID and what changed' },
      { ja: '影響を受けるフェーズ・成果物・アーキテクチャ構成要素', en: 'Affected phases, deliverables, and architecture components' },
      { ja: '影響の大きさ(工数、スケジュール、コスト)', en: 'Size of impact: effort, schedule, cost' },
      { ja: '再作業の要否と、差し戻し先フェーズ', en: 'Whether rework is required and which phase it goes back to' },
      { ja: '判断と承認者', en: 'The decision and who approved it' },
    ],
    tips: [
      { ja: '「影響なし」と判断した場合もその判断を記録する。後で問題になったときの根拠になる。', en: 'Record "no impact" verdicts too. They are your evidence when it later turns out otherwise.' },
      { ja: '影響評価を省略した変更が、後工程で最も高くつく。', en: 'The changes that skip impact assessment are the ones that cost the most downstream.' },
    ],
    keywords: ['requirements', '要件', '影響評価', 'impact', '変更', 'change', '再作業', 'rework'],
    template: [
      { heading: { ja: '1. 対象要件と変更内容', en: '1. Requirement and Change' }, guidance: { ja: '要件 ID、変更前後の記述、提起者、提起日。差分を書かずに変更後だけ書くと、後で何が変わったか追えない。', en: 'Requirement ID, the statement before and after, who raised it, and when. Recording only the new wording makes the change untraceable later.' } },
      { heading: { ja: '2. 変更の理由', en: '2. Reason for the Change' }, guidance: { ja: 'なぜ今この変更が必要かを提起者の言葉で書く。理由の弱い変更の半分はこの節で自然に止まる。', en: 'Why it is needed now, in the requester\'s own words. Half of the weakly motivated changes stop right here on their own.' } },
      { heading: { ja: '3. 影響範囲', en: '3. Scope of Impact' }, guidance: { ja: '影響先 / 種別(フェーズ・成果物・構成要素) / 影響内容 / 確認者 の 4 列の表で。「影響なし」と判断したものも行として残す。', en: 'A four-column table: affected item, type (phase, deliverable, component), nature of impact, who checked. Keep the "no impact" rows too.' } },
      { heading: { ja: '4. 影響の大きさ', en: '4. Size of Impact' }, guidance: { ja: '工数・スケジュール・コストを幅(最小〜最大)で見積もる。単一の数字を出すと、後で必ずその数字だけが独り歩きする。', en: 'Estimate effort, schedule, and cost as a range. Give a single number and that number will travel alone from then on.' } },
      { heading: { ja: '5. 再作業の要否と差し戻し先', en: '5. Rework and Where It Goes Back To' }, guidance: { ja: '差し戻すフェーズと、そこからやり直す範囲。差し戻さずに済ませる代替案も併記して、比較できる形にする。', en: 'Which phase it returns to and how much is redone. Put the no-rework alternative alongside it so the two can be compared.' } },
      { heading: { ja: '6. 判断と条件', en: '6. Decision and Conditions' }, guidance: { ja: '承認 / 却下 / 保留と、その条件。却下の場合も理由を残す。理由なき却下は形を変えて必ず戻ってくる。', en: 'Approved, rejected, or deferred, with the conditions. Record the reason for rejections too — an unexplained one always returns in a new shape.' } },
      { heading: { ja: '7. 承認', en: '7. Approval' }, guidance: { ja: '承認者名・役職・日付。作業範囲記述書の再承認が必要かどうかをここで明記する。', en: 'Approver name, title, date. State here whether the Statement of Architecture Work needs re-approval.' } },
    ],
  },
  {
    id: 'architecture-repository',
    name: { ja: 'アーキテクチャリポジトリ', en: 'Architecture Repository' },
    summary: {
      ja: 'アーキテクチャ成果物・標準・参照モデル・決定記録を保管し、再利用可能にする仕組み。個々の成果物ではなく「資産の蓄積」を扱う点が特徴。',
      en: 'The store that holds architecture deliverables, standards, reference models, and decision records, and makes them reusable. Its subject is the accumulating asset base rather than any single deliverable.',
    },
    createdInPhaseIds: ['preliminary'],
    refinedInPhaseIds: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    contents: [
      { ja: '現行・目標のアーキテクチャ記述', en: 'Baseline and target architecture descriptions' },
      { ja: '標準情報(技術標準、規制、データ定義)', en: 'Standards information: technology standards, regulations, data definitions' },
      { ja: '参照モデル・再利用可能な構成要素', en: 'Reference models and reusable building blocks' },
      { ja: 'ガバナンス記録(決定ログ、例外台帳、適合性評価)', en: 'Governance records: decision log, exception register, compliance assessments' },
      { ja: '版管理と公開範囲', en: 'Versioning and access scope' },
    ],
    tips: [
      { ja: '検索できないリポジトリは存在しないのと同じ。命名規則と索引を先に決める。', en: 'A repository you cannot search does not exist. Decide naming conventions and the index first.' },
      { ja: '専用ツールにこだわらない。既存のドキュメント基盤 + 明確な構造で十分機能する。', en: 'Do not hold out for a dedicated tool. An existing document platform plus a clear structure works well enough.' },
      { ja: '決定ログ(なぜそう決めたか)が最も再利用される資産になる。', en: 'The decision log — why things were decided — turns out to be the most reused asset of all.' },
    ],
    keywords: ['repository', 'リポジトリ', '資産', 'asset', '再利用', 'reuse', '決定ログ', 'decision log'],
    template: [
      { heading: { ja: '1. 目的と利用者', en: '1. Purpose and Users' }, guidance: { ja: '誰が何を探しに来るのかを具体的に 3 つ挙げる。想定利用シーンの無いリポジトリは、分類だけが立派になって誰も開かない。', en: 'Name three concrete things people come looking for. A repository with no imagined use ends up with a beautiful taxonomy nobody opens.' } },
      { heading: { ja: '2. 収める資産の分類', en: '2. Asset Categories' }, guidance: { ja: '現行 / 目標の記述、標準情報、参照モデル、再利用可能な構成要素、ガバナンス記録 の 5 区分と、各区分の受け入れ基準を書く。', en: 'Five categories — baseline and target descriptions, standards information, reference models, reusable building blocks, governance records — each with its acceptance criteria.' } },
      { heading: { ja: '3. 命名規則と識別子', en: '3. Naming and Identifiers' }, guidance: { ja: '文書 ID と版番号の付け方を決める。運用開始後は変えられないので、ここは最初に時間をかける。', en: 'Fix the document ID and version numbering scheme. It cannot be changed once in use, so spend the time here first.' } },
      { heading: { ja: '4. 検索の仕組み', en: '4. How Things Are Found' }, guidance: { ja: '索引・タグ・全文検索のどれで探せるようにするかを決める。検索できないリポジトリは、存在しないのと同じ。', en: 'Decide whether retrieval is by index, tags, or full-text search. A repository you cannot search does not exist.' } },
      { heading: { ja: '5. 版管理と公開範囲', en: '5. Versioning and Access' }, guidance: { ja: '版の確定タイミング、旧版の保持方針、閲覧・編集権限を書く。機密区分ごとの扱いも含める。', en: 'When a version is frozen, how old versions are kept, and who may read or edit. Include handling per sensitivity class.' } },
      { heading: { ja: '6. 登録と廃棄の手順', en: '6. Registration and Retirement' }, guidance: { ja: '誰がいつ登録し、いつ「もう有効でない」と印を付けるか。古い版が現役の顔で残っている状態が、最も害が大きい。', en: 'Who registers what and when, and when something is marked no longer current. The worst state is an obsolete version still posing as live.' } },
      { heading: { ja: '7. 決定ログ', en: '7. Decision Log' }, guidance: { ja: '決定内容だけでなく、検討した代替案と却下理由を残す。最も再利用される資産は、結局ここになる。', en: 'Record not just the decision but the alternatives considered and why they were rejected. This turns out to be the most reused asset of all.' } },
      { heading: { ja: '8. 運用の責任者と点検', en: '8. Ownership and Housekeeping' }, guidance: { ja: '管理責任者と、年 1 回程度の棚卸しの手順を決める。責任者不在のリポジトリは 2 年で誰も信用しなくなる。', en: 'Name the custodian and define an annual housekeeping pass. An ownerless repository loses everyone\'s trust within two years.' } },
    ],
  },
];

export function findDeliverable(id: string): Deliverable | undefined {
  const key = id.trim().toLowerCase();
  return (
    DELIVERABLES.find((d) => d.id === key) ??
    DELIVERABLES.find((d) => d.name.en.toLowerCase() === key || d.name.ja === id.trim())
  );
}
